// Code generated by alef — DO NOT EDIT.
// alef:hash:f757a8d7afe26bc4beade1ee164cb85525f85b3a7092bd45513893e69b611b14
package literllm

// RequireNativeSetup_2_0_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_2_0_0 = "2.0.0"
