// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:454fbd3bd48bfb9cc75b06f570a858d1eb56da37f48d46155d1bc0412ba481d2
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
    name: "E2eSwift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    dependencies: [
        .package(path: "../../packages/swift"),
    ],
    targets: [
        .testTarget(
            name: "LiterLlmE2ETests",
            dependencies: [.product(name: "LiterLlm", package: "swift")]
        ),
    ]
)
