// Generated by alef. Do not edit by hand.
// alef:hash:8732a575186d52bb8f304d96c3f130846ad0e64645d1c4d016ab16c83f9218e4
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Auth configuration block. */
data class AuthConfig(
    /** Auth scheme classification. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("type")
    @param:com.fasterxml.jackson.annotation.JsonProperty("type")
    val authType: AuthType,
    /**
     * Name of the environment variable that holds the API key (e.g. `"OPENAI_API_KEY"`).
     * Holds the variable name, never the secret value.
     */
    val envVar: String? = null,
)
