// Generated by alef. Do not edit by hand.
// alef:hash:af58d56b0ad0d7f32cb19b40e606e048dd74a6068b66484f2aec4310dd43fc20
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** A tool the model can invoke (currently, all tools are functions). */
data class ChatCompletionTool(
    /** Tool type (always "function" in OpenAI spec). */
    @get:com.fasterxml.jackson.annotation.JsonProperty("type")
    @param:com.fasterxml.jackson.annotation.JsonProperty("type")
    val toolType: ToolType,
    /** Function definition with name, description, and JSON schema parameters. */
    val function: FunctionDefinition,
)
