// Generated by alef. Do not edit by hand.
// alef:hash:282044d9d1d8f7e1a47812a3bd4d26977c740f116576c5d97ff4e0b28079d8ea
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
    "LongMethod",
)

package io.xberg.literllm.android

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.withContext

@Suppress("TooManyFunctions")
class DefaultClient internal constructor(handle: Long) : AutoCloseable {
    private val handleLock = Any()
    private var nativeHandle: Long = handle

    private inline fun <T> withHandle(block: (Long) -> T): T = synchronized(handleLock) {
        check(nativeHandle != 0L) { "DefaultClient is closed" }
        block(nativeHandle)
    }
    companion object {
        private val MAPPER = com.fasterxml.jackson.databind.ObjectMapper()
            .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
            .findAndRegisterModules()
            .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
            .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    }

    suspend fun chat(req: ChatCompletionRequest): ChatCompletionResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientChat(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, ChatCompletionResponse::class.java)
        }
    }

    suspend fun embed(req: EmbeddingRequest): EmbeddingResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientEmbed(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, EmbeddingResponse::class.java)
        }
    }

    suspend fun listModels(): ModelsListResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientListModels(handle) }
            MAPPER.readValue(responseJson, ModelsListResponse::class.java)
        }
    }

    suspend fun imageGenerate(req: CreateImageRequest): ImagesResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientImageGenerate(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, ImagesResponse::class.java)
        }
    }

    suspend fun speech(req: CreateSpeechRequest): ByteArray {
        return withContext(Dispatchers.IO) { withHandle { handle -> LiterLlmBridge.nativeDefaultClientSpeech(handle, MAPPER.writeValueAsString(req)) } }
    }

    suspend fun transcribe(req: CreateTranscriptionRequest): TranscriptionResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientTranscribe(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, TranscriptionResponse::class.java)
        }
    }

    suspend fun moderate(req: ModerationRequest): ModerationResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientModerate(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, ModerationResponse::class.java)
        }
    }

    suspend fun rerank(req: RerankRequest): RerankResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientRerank(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, RerankResponse::class.java)
        }
    }

    suspend fun search(req: SearchRequest): SearchResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientSearch(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, SearchResponse::class.java)
        }
    }

    suspend fun ocr(req: OcrRequest): OcrResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientOcr(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, OcrResponse::class.java)
        }
    }

    suspend fun createFile(req: CreateFileRequest): FileObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientCreateFile(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, FileObject::class.java)
        }
    }

    suspend fun retrieveFile(fileId: String): FileObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientRetrieveFile(handle, MAPPER.writeValueAsString(fileId)) }
            MAPPER.readValue(responseJson, FileObject::class.java)
        }
    }

    suspend fun deleteFile(fileId: String): DeleteResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientDeleteFile(handle, MAPPER.writeValueAsString(fileId)) }
            MAPPER.readValue(responseJson, DeleteResponse::class.java)
        }
    }

    suspend fun listFiles(query: FileListQuery? = null): FileListResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientListFiles(handle, query?.let { MAPPER.writeValueAsString(it) } ?: "") }
            MAPPER.readValue(responseJson, FileListResponse::class.java)
        }
    }

    suspend fun fileContent(fileId: String): ByteArray {
        return withContext(Dispatchers.IO) { withHandle { handle -> LiterLlmBridge.nativeDefaultClientFileContent(handle, MAPPER.writeValueAsString(fileId)) } }
    }

    suspend fun createBatch(req: CreateBatchRequest): BatchObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientCreateBatch(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, BatchObject::class.java)
        }
    }

    suspend fun retrieveBatch(batchId: String): BatchObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientRetrieveBatch(handle, MAPPER.writeValueAsString(batchId)) }
            MAPPER.readValue(responseJson, BatchObject::class.java)
        }
    }

    suspend fun listBatches(query: BatchListQuery? = null): BatchListResponse {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientListBatches(handle, query?.let { MAPPER.writeValueAsString(it) } ?: "") }
            MAPPER.readValue(responseJson, BatchListResponse::class.java)
        }
    }

    suspend fun cancelBatch(batchId: String): BatchObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientCancelBatch(handle, MAPPER.writeValueAsString(batchId)) }
            MAPPER.readValue(responseJson, BatchObject::class.java)
        }
    }

    suspend fun fetchBatchForPolling(batchId: String): BatchObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientFetchBatchForPolling(handle, MAPPER.writeValueAsString(batchId)) }
            MAPPER.readValue(responseJson, BatchObject::class.java)
        }
    }

    // Poll a batch until it reaches a terminal status (Completed, Failed, Expired, Cancelled).
    //
    // Uses exponential backoff with configurable initial interval, maximum interval, and backoff multiplier.
    // Optionally supports a timeout that aborts polling if exceeded.
    //
    // # Errors
    //
    // Returns `BatchWaitError::Failed` if the batch reaches a failure terminal status.
    // Returns `BatchWaitError::Timeout` if the configured timeout is exceeded.
    // Returns `BatchWaitError::Client` for underlying client errors.
    //
    // # Example
    //
    // ```no_run
    // # use liter_llm::client::{DefaultClient, ClientConfig, WaitForBatchConfig};
    // # async fn run() -> Result<(), Box<dyn std::error::Error>> {
    // let client = DefaultClient::new(ClientConfig::new("api-key"), None)?;
    // let batch = client.wait_for_batch("b-123", WaitForBatchConfig::default()).await?;
    // println!("Batch completed: {:?}", batch.status);
    // # Ok(())
    // # }
    // ```
    suspend fun waitForBatch(batchId: String, config: WaitForBatchConfig): BatchObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientWaitForBatch(handle, MAPPER.writeValueAsString(mapOf("batchId" to batchId, "config" to config))) }
            MAPPER.readValue(responseJson, BatchObject::class.java)
        }
    }

    suspend fun createResponse(req: CreateResponseRequest): ResponseObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientCreateResponse(handle, MAPPER.writeValueAsString(req)) }
            MAPPER.readValue(responseJson, ResponseObject::class.java)
        }
    }

    suspend fun retrieveResponse(responseId: String): ResponseObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientRetrieveResponse(handle, MAPPER.writeValueAsString(responseId)) }
            MAPPER.readValue(responseJson, ResponseObject::class.java)
        }
    }

    suspend fun cancelResponse(responseId: String): ResponseObject {
        return withContext(Dispatchers.IO) {
            val responseJson = withHandle { handle -> LiterLlmBridge.nativeDefaultClientCancelResponse(handle, MAPPER.writeValueAsString(responseId)) }
            MAPPER.readValue(responseJson, ResponseObject::class.java)
        }
    }

    @Suppress("TooGenericExceptionCaught")
    fun chatStream(req: ChatCompletionRequest): kotlinx.coroutines.flow.Flow<ChatCompletionChunk> = kotlinx.coroutines.flow.callbackFlow {
        val mapper = com.fasterxml.jackson.databind.ObjectMapper()
            .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
            .findAndRegisterModules()
            .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
        val streamHandle: Long = withContext(Dispatchers.IO) {
            withHandle { handle ->
                LiterLlmBridge.nativeDefaultClientChatStreamStart(handle, mapper.writeValueAsString(req))
            }
        }
        try {
            while (true) {
                val chunkJson: String? = withContext(Dispatchers.IO) {
                    LiterLlmBridge.nativeDefaultClientChatStreamNext(streamHandle)
                }
                if (chunkJson == null) break
                val chunk = mapper.readValue(chunkJson, ChatCompletionChunk::class.java)
                send(chunk)
            }
            close()
        } catch (e: Throwable) {
            close(e)
        }
        awaitClose {
            LiterLlmBridge.nativeDefaultClientChatStreamFree(streamHandle)
        }
    }
    override fun close() = synchronized(handleLock) {
        if (nativeHandle != 0L) {
            val handle = nativeHandle
            nativeHandle = 0L
            LiterLlmBridge.nativeFreeDefaultClient(handle)
        }
    }
}
