// Generated by alef. Do not edit by hand.
// alef:hash:0d08cfc1842c99e03bc96def72b45c3a328bbfb5a6a250f7ab10c96fc2b86bf8
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Boolean flags for each moderation category. */
data class ModerationCategories(
    /** Sexual content. */
    val sexual: Boolean = false,
    /** Hate speech. */
    val hate: Boolean = false,
    /** Harassment. */
    val harassment: Boolean = false,
    /** Self-harm content. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("self-harm")
    @param:com.fasterxml.jackson.annotation.JsonProperty("self-harm")
    val selfHarm: Boolean = false,
    /** Sexual content involving minors. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("sexual/minors")
    @param:com.fasterxml.jackson.annotation.JsonProperty("sexual/minors")
    val sexualMinors: Boolean = false,
    /** Hate speech that threatens violence. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("hate/threatening")
    @param:com.fasterxml.jackson.annotation.JsonProperty("hate/threatening")
    val hateThreatening: Boolean = false,
    /** Graphic violence. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("violence/graphic")
    @param:com.fasterxml.jackson.annotation.JsonProperty("violence/graphic")
    val violenceGraphic: Boolean = false,
    /** Intent to self-harm. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("self-harm/intent")
    @param:com.fasterxml.jackson.annotation.JsonProperty("self-harm/intent")
    val selfHarmIntent: Boolean = false,
    /** Instructions for self-harm. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("self-harm/instructions")
    @param:com.fasterxml.jackson.annotation.JsonProperty("self-harm/instructions")
    val selfHarmInstructions: Boolean = false,
    /** Harassment that threatens violence. */
    @get:com.fasterxml.jackson.annotation.JsonProperty("harassment/threatening")
    @param:com.fasterxml.jackson.annotation.JsonProperty("harassment/threatening")
    val harassmentThreatening: Boolean = false,
    /** Non-graphic violence. */
    val violence: Boolean = false,
)
