// Generated by alef. Do not edit by hand.
// alef:hash:3a041f53d81ef3f3da3133b1e96c72dad834036a02fcb6777252571e59960ec4
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** A single output item from the response. */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class ResponseOutputItem(
    /** Output type (e.g., `"text"`, `"object"`, `"error"`). */
    @get:com.fasterxml.jackson.annotation.JsonProperty("type")
    @param:com.fasterxml.jackson.annotation.JsonProperty("type")
    val itemType: String = "",
    /** Output content (flattened into the object). */
    val content: Any? = null,
)
