// Generated by alef. Do not edit by hand.
// alef:hash:af2656dc9dd652971427a6bbd56387fec3589ff937ca50b8fbfaaf35d2e8a24e
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Directive to call a specific tool. */
data class SpecificToolChoice(
    /** Tool type (always "function"). */
    @get:com.fasterxml.jackson.annotation.JsonProperty("type")
    @param:com.fasterxml.jackson.annotation.JsonProperty("type")
    val choiceType: ToolType = ToolType.FUNCTION,
    /** The specific function to invoke. */
    val function: SpecificFunction = SpecificFunction(),
)
