<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:107db15610212e026eee3df314b54eea64670e1f0bb6de58d16a632e3f705fe8
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\CreateBatchRequest;

/** E2e tests for category: batches. */
final class BatchesTest extends TestCase
{


    /** Attempt to cancel an already-cancelled batch */
    public function test_edge_batch_already_cancelled(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_batch_already_cancelled');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->cancelBatch("batch-cancelled001");
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** List batches when no batches exist */
    public function test_edge_batch_empty_list(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_batch_empty_list');
        $result = $client->listBatches();
        $data = $result->getData();

            $this->assertCount(0, $data);


    }


    /** 401 Unauthorized when creating a batch with invalid API key */
    public function test_error_batch_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_batch_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateBatchRequest::from_json(json_encode(["completionWindow" => "24h", "endpoint" => "/v1/chat/completions", "inputFileId" => "file-abc123"]));
        $client->createBatch($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request when creating a batch with invalid input file */
    public function test_error_batch_invalid_file(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_batch_invalid_file');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateBatchRequest::from_json(json_encode(["completionWindow" => "24h", "endpoint" => "/v1/chat/completions", "inputFileId" => "file-wrong-purpose"]));
        $client->createBatch($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 404 Not Found when retrieving a nonexistent batch */
    public function test_error_batch_not_found(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_batch_not_found');
        // skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->retrieveBatch("batch-nonexistent");
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Retrieve a completed batch job with output file */
    public function test_smoke_batch_completed(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_batch_completed');
        $result = $client->retrieveBatch("batch-ghi789");

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');
            $this->assertEquals("completed", $result->status);


    }


    /** Cancel a running batch job */
    public function test_smoke_cancel_batch(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_cancel_batch');
        $result = $client->cancelBatch("batch-def456");

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');
            $this->assertEquals("cancelling", $result->status);


    }


    /** Create a new batch processing job */
    public function test_smoke_create_batch(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_create_batch');
        $req = \Liter\Llm\CreateBatchRequest::from_json(json_encode(["completionWindow" => "24h", "endpoint" => "/v1/chat/completions", "inputFileId" => "file-abc123"]));
        $result = $client->createBatch($req);

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');
            $this->assertEquals("validating", $result->status);


    }


    /** List all batch jobs */
    public function test_smoke_list_batches(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_list_batches');
        $result = $client->listBatches();
        $data = $result->getData();

            $this->assertCount(2, $data);


    }


    /** Retrieve the status of a batch job */
    public function test_smoke_retrieve_batch(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_retrieve_batch');
        $result = $client->retrieveBatch("batch-abc123");

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');
            $this->assertEquals("in_progress", $result->status);


    }

}
