<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb0d35357f30dc432362923113141f246af89c446ce05d34ee770e280a345304
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\EmbeddingRequest;

/** E2e tests for category: embed. */
final class EmbedTest extends TestCase
{


    /** Embedding request with multiple input strings returns one embedding object per input */
    public function test_batch_embed(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/batch_embed');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["input" => ["Hello", "World"], "model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();
        $data0Embedding = $result->getData()[0]->embedding;

            $this->assertCount(2, $data);
            $this->assertCount(5, $data0Embedding);


    }


    /** Embedding request with multiple inputs returns multiple embedding objects */
    public function test_edge_embed_batch_input(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_embed_batch_input');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["input" => ["Hello world", "Goodbye world"], "model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();

            $this->assertCount(2, $data);
            $this->assertEquals(0, $result->getData()[0]->index);
            $this->assertEquals(1, $result->getData()[1]->index);


    }


    /** Embedding request with empty string input returns empty data array */
    public function test_edge_embed_empty_input(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_embed_empty_input');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();

            $this->assertCount(0, $data);


    }


    /** Embedding request with encoding_format base64 decodes to a float array embedding */
    public function test_embed_base64(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/embed_base64');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["encodingFormat" => "base64", "input" => "Test input", "model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();
        $data0Embedding = $result->getData()[0]->embedding;

            $this->assertCount(1, $data);
            $this->assertCount(4, $data0Embedding);


    }


    /** Embedding request with explicit encoding_format of float returns float array embeddings */
    public function test_embed_encoding_format(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/embed_encoding_format');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["encodingFormat" => "float", "input" => "Test input", "model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();
        $data0Embedding = $result->getData()[0]->embedding;

            $this->assertCount(1, $data);
            $this->assertCount(5, $data0Embedding);


    }


    /** 401 Unauthorized error on embedding request when API key is invalid */
    public function test_embed_error_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/embed_error_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["input" => "Hello world", "model" => "text-embedding-3-small"]));
        $client->embed($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Embedding request with explicit dimensions parameter returns embeddings of the requested size */
    public function test_embed_with_dimensions(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/embed_with_dimensions');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["dimensions" => 256, "input" => "Hello world", "model" => "text-embedding-3-small"]));
        $result = $client->embed($req);
        $data = $result->getData();
        $data0Embedding = $result->getData()[0]->embedding;

            $this->assertCount(1, $data);
            $this->assertCount(8, $data0Embedding);


    }


    /** Embedding request via Ollama local provider with all-minilm model */
    public function test_local_embed_ollama(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/local_embed_ollama');
        $req = \Liter\Llm\EmbeddingRequest::from_json(json_encode(["input" => "The quick brown fox jumps over the lazy dog", "model" => "ollama/all-minilm"]));
        $result = $client->embed($req);
        $data = $result->getData();
        $data0Embedding = $result->getData()[0]->embedding;

            $this->assertCount(1, $data);
            $this->assertCount(32, $data0Embedding);


    }

}
