<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0db22588626f9090816b43858dab2752858e92ae545aaf3b473fe2c9659dddb
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;

/** E2e tests for category: list-models. */
final class ListModelsTest extends TestCase
{


    /** List models response returns an empty data array when no models are available */
    public function test_empty_model_list(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/empty_model_list');
        $result = $client->listModels();
        $data = $result->getData();

            $this->assertGreaterThanOrEqual(0, count($data));
            $this->assertCount(0, $data);


    }


    /** 401 Unauthorized error on list models request when API key is invalid */
    public function test_list_models_error_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/list_models_error_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->listModels();
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 500 Internal Server Error when listing models due to server failure */
    public function test_list_models_error_500(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/list_models_error_500');
        // skipped: declared error variant 'ServerError' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->listModels();
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** List models response with multiple model objects */
    public function test_list_models_filtered(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/list_models_filtered');
        $result = $client->listModels();
        $data = $result->getData();

            $this->assertGreaterThanOrEqual(5, count($data));
            $this->assertEquals("model", $result->getData()[0]->object);


    }

}
