<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0aa6e96bdd0306ac346c34c13033e22691d6406984f6eb175f7ad31cfb7ace64
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\RerankRequest;

/** E2e tests for category: rerank. */
final class RerankTest extends TestCase
{


    /** Reranking with an empty query string */
    public function test_edge_rerank_empty_query(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_rerank_empty_query');
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["Some document", "Another document"], "model" => "rerank-v3.5", "query" => ""]));
        $result = $client->rerank($req);
        $results = $result->getResults();

            $this->assertCount(2, $results);


    }


    /** Reranking with only a single document */
    public function test_edge_rerank_single_doc(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_rerank_single_doc');
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["Artificial intelligence is the simulation of human intelligence."], "model" => "rerank-v3.5", "query" => "What is AI?"]));
        $result = $client->rerank($req);
        $results = $result->getResults();

            $this->assertCount(1, $results);
            $this->assertGreaterThan(0.9, $result->getResults()[0]->relevanceScore);


    }


    /** 401 Unauthorized for reranking with invalid API key */
    public function test_error_rerank_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_rerank_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["doc1"], "model" => "rerank-v3.5", "query" => "test"]));
        $client->rerank($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request for reranking with invalid model */
    public function test_error_rerank_bad_request(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_rerank_bad_request');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["doc1"], "model" => "nonexistent-rerank", "query" => "test"]));
        $client->rerank($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Basic reranking of documents against a query */
    public function test_smoke_rerank_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_rerank_basic');
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["Machine learning is a subset of AI.", "The weather is sunny today.", "Deep learning uses neural networks."], "model" => "rerank-v3.5", "query" => "What is machine learning?"]));
        $result = $client->rerank($req);
        $results = $result->getResults();

            $this->assertCount(3, $results);
            $this->assertGreaterThan(0.9, $result->getResults()[0]->relevanceScore);


    }


    /** Reranking with return_documents flag to include document text */
    public function test_smoke_rerank_return_docs(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_rerank_return_docs');
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["Rust is a systems programming language.", "Iron rusts when exposed to water."], "model" => "rerank-v3.5", "query" => "What is Rust?", "returnDocuments" => true]));
        $result = $client->rerank($req);
        $results = $result->getResults();

            $this->assertCount(2, $results);
            $this->assertNotSame('', ($result->getResults()[0]->getDocument() ?? null) ?? '', 'expected non-empty value');
            $this->assertGreaterThan(0.9, $result->getResults()[0]->relevanceScore);


    }


    /** Reranking with top_n parameter to limit results */
    public function test_smoke_rerank_with_top_n(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_rerank_with_top_n');
        $req = \Liter\Llm\RerankRequest::from_json(json_encode(["documents" => ["Python is a programming language.", "Cats are cute animals.", "Python was created by Guido van Rossum.", "The sun is a star."], "model" => "rerank-v3.5", "query" => "What is Python?", "topN" => 2]));
        $result = $client->rerank($req);
        $results = $result->getResults();

            $this->assertCount(2, $results);
            $this->assertGreaterThan(0.9, $result->getResults()[0]->relevanceScore);


    }

}
