// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40f578f8621e4708d13dbd7b2cf5019c9e32e4b1341919a989cc21fea3d1e523
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: chat
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/liter-llm/packages/go"
)

func Test_DeveloperMessage(t *testing.T) {
	// Chat request that includes a developer role message alongside user messages
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"You are a coding assistant. Always respond with concise code examples.","role":"developer"},{"content":"How do I reverse a string in Python?","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/developer_message"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0MessageContent string
	if result.Choices[0].Message.Content != nil {
		choices0MessageContent = result.Choices[0].Message.Content.Text()
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0MessageContent) != `s[::-1]` {
		t.Errorf("equals mismatch: got %v", choices0MessageContent)
	}
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_EdgeChatMaxTokens(t *testing.T) {
	// Chat request with max_tokens=1 terminates with length finish_reason
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"max_tokens":1,"messages":[{"content":"Write a story","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/edge_chat_max_tokens"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	if string(choices0FinishReason) != `length` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
	if len(result.Choices) == 0 {
		t.Fatalf("expected non-empty %s", `result.Choices`)
	}
	if result.Choices[0].Message.Content == nil {
		t.Errorf("expected non-empty value")
	}
}

func Test_EdgeChatSystemOnly(t *testing.T) {
	// Chat request with system message and user message
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"You are a helpful and concise assistant","role":"system"},{"content":"Hi","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/edge_chat_system_only"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Choices[0].Message.Content == nil {
		t.Errorf("expected non-empty value")
	}
}

func Test_EdgeChatTemperatureZero(t *testing.T) {
	// Chat request with temperature=0 for deterministic responses
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Say hello","role":"user"}],"model":"gpt-4","temperature":0}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/edge_chat_temperature_zero"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Choices[0].Message.Content == nil {
		t.Errorf("expected non-empty value")
	}
}

func Test_FinishReasonContentFilter(t *testing.T) {
	// Chat response stopped by content filter with finish_reason of content_filter and null content
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Tell me something controversial","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/finish_reason_content_filter"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0FinishReason) != `content_filter` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_FinishReasonLength(t *testing.T) {
	// Chat response truncated due to max_tokens limit with finish_reason of length
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"max_tokens":5,"messages":[{"content":"Tell me a long story","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/finish_reason_length"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0FinishReason) != `length` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_MultiTurnConversation(t *testing.T) {
	// Multi-turn conversation with system, user, assistant, and follow-up user messages
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"You are a helpful assistant.","role":"system"},{"content":"What is 2 + 2?","role":"user"},{"content":"2 + 2 equals 4.","role":"assistant"},{"content":"And what is 4 + 4?","role":"user"}],"model":"gpt-4"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/multi_turn_conversation"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0MessageContent string
	if result.Choices[0].Message.Content != nil {
		choices0MessageContent = result.Choices[0].Message.Content.Text()
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0MessageContent) != `4 + 4 equals 8.` {
		t.Errorf("equals mismatch: got %v", choices0MessageContent)
	}
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_ParallelToolCalls(t *testing.T) {
	// Chat request that results in parallel tool calls in the response
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"What is the weather in NYC and London?","role":"user"}],"model":"gpt-4","parallel_tool_calls":true,"tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city name","type":"string"}},"required":["location"],"type":"object"}},"type":"function"}]}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/parallel_tool_calls"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if result.Choices[0].Message.ToolCalls == nil || len(result.Choices[0].Message.ToolCalls) == 0 {
		t.Errorf("expected non-empty value")
	}
	if result.Choices[0].Message.ToolCalls != nil {
		assert.Equal(t, len(result.Choices[0].Message.ToolCalls), 2, "expected exactly 2 elements")
	}
	if string(choices0FinishReason) != `tool_calls` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_ResponseFormatJsonObject(t *testing.T) {
	// Chat request with response_format json_object that returns valid JSON content
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Respond with JSON only.","role":"system"},{"content":"Give me a user object with name and age fields.","role":"user"}],"model":"gpt-4","response_format":{"type":"json_object"}}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/response_format_json_object"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if result.Choices[0].Message.Content == nil {
		t.Errorf("expected non-empty value")
	}
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_ResponseFormatJsonSchema(t *testing.T) {
	// Chat request with response_format json_schema that validates the output structure
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"What is the temperature in Paris today?","role":"user"}],"model":"gpt-4","response_format":{"json_schema":{"name":"weather","schema":{"properties":{"temp":{"type":"number"}},"required":["temp"],"type":"object"}},"type":"json_schema"}}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/response_format_json_schema"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if result.Choices[0].Message.Content == nil {
		t.Errorf("expected non-empty value")
	}
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_SeedParameter(t *testing.T) {
	// Chat request with seed parameter for deterministic output; response includes system_fingerprint
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Pick a random number","role":"user"}],"model":"gpt-4","seed":42}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/seed_parameter"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
	if result.SystemFingerprint == nil {
		t.Errorf("expected non-empty value")
	}
}

func Test_StopSequences(t *testing.T) {
	// Chat request with custom stop sequences that terminates generation at a stop token
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"List items until you see STOP","role":"user"}],"model":"gpt-4","stop":["STOP","END"]}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/stop_sequences"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_ToolChoiceRequired(t *testing.T) {
	// Chat request with tool_choice set to required forces the model to call a tool
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"What is the weather today?","role":"user"}],"model":"gpt-4","tool_choice":"required","tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city name","type":"string"}},"required":["location"],"type":"object"}},"type":"function"}]}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/tool_choice_required"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if result.Choices[0].Message.ToolCalls == nil || len(result.Choices[0].Message.ToolCalls) == 0 {
		t.Errorf("expected non-empty value")
	}
	if result.Choices[0].Message.ToolCalls != nil {
		if len(result.Choices) == 0 {
			t.Fatalf("expected non-empty %s", `result.Choices`)
		}
		if string(result.Choices[0].Message.ToolCalls[0].Function.Name) != `get_weather` {
			t.Errorf("equals mismatch: got %v", result.Choices[0].Message.ToolCalls[0].Function.Name)
		}
	} else {
		t.Errorf("expected %s to be present, got nil", `result.Choices[0].Message.ToolCalls`)
	}
	if string(choices0FinishReason) != `tool_calls` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}

func Test_ToolChoiceSpecific(t *testing.T) {
	// Chat request with tool_choice specifying a particular function to call
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"What is the weather in Paris?","role":"user"}],"model":"gpt-4","tool_choice":{"function":{"name":"get_weather"},"type":"function"},"tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city name","type":"string"}},"required":["location"],"type":"object"}},"type":"function"},{"function":{"description":"Search the web for information","name":"search_web","parameters":{"properties":{"query":{"description":"The search query","type":"string"}},"required":["query"],"type":"object"}},"type":"function"}]}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/tool_choice_specific"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if result.Choices[0].Message.ToolCalls == nil || len(result.Choices[0].Message.ToolCalls) == 0 {
		t.Errorf("expected non-empty value")
	}
	if result.Choices[0].Message.ToolCalls != nil {
		if len(result.Choices) == 0 {
			t.Fatalf("expected non-empty %s", `result.Choices`)
		}
		if string(result.Choices[0].Message.ToolCalls[0].Function.Name) != `get_weather` {
			t.Errorf("equals mismatch: got %v", result.Choices[0].Message.ToolCalls[0].Function.Name)
		}
	} else {
		t.Errorf("expected %s to be present, got nil", `result.Choices[0].Message.ToolCalls`)
	}
	if string(choices0FinishReason) != `tool_calls` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
}
