// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e07ef53f345f44579b4d91b56a9a68c8dca9fe43c9a0b082efaede9fe26deda5
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: contract
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_BindingApiParity(t *testing.T) {
	// Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Contract test","role":"user"}],"model":"openai/gpt-4o"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/binding_api_parity"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0MessageContent string
	if result.Choices[0].Message.Content != nil {
		choices0MessageContent = result.Choices[0].Message.Content.Text()
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if string(choices0MessageContent) != `OK` {
		t.Errorf("equals mismatch: got %v", choices0MessageContent)
	}
	if string(choices0FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
	if result.Usage.TotalTokens != 6 {
		t.Errorf("equals mismatch: got %v", result.Usage.TotalTokens)
	}
	if string(result.Model) != `gpt-4o` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_ContractOcr(t *testing.T) {
	// Verify ocr() method exists in all bindings
	var req pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"https://example.com/contract-test.pdf"},"model":"mistral/mistral-ocr-latest"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/contract_ocr"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Ocr(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ContractSearch(t *testing.T) {
	// Verify search() method exists in all bindings
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":"contract test query"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/contract_search"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
