// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bbdf651c6560ce7087732157a9b311ebe8e21f626a321e971beacac181732272
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: speech
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_EdgeSpeechAllVoices(t *testing.T) {
	// Text-to-speech with specific voice selection
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"Hello world","model":"tts-1","voice":"nova"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/edge_speech_all_voices"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Speech(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	value := result
	if len(value) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_EdgeSpeechLongInput(t *testing.T) {
	// Speech generation with a very long input text
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.","model":"tts-1","voice":"echo"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/edge_speech_long_input"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Speech(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	value := result
	if len(value) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_ErrorSpeechAuth401(t *testing.T) {
	// 401 Unauthorized for speech generation with invalid API key
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"Hello","model":"tts-1","voice":"alloy"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/error_speech_auth_401"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Speech(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'Authentication' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_ErrorSpeechBadModel(t *testing.T) {
	// 400 Bad Request for speech with unsupported model
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"Hello","model":"tts-nonexistent","voice":"alloy"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/error_speech_bad_model"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Speech(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'BadRequest' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_SmokeSpeechBasic(t *testing.T) {
	// Basic text-to-speech generation
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"Hello, world!","model":"tts-1","voice":"alloy"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/smoke_speech_basic"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Speech(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	value := result
	if len(value) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_SmokeSpeechMp3Format(t *testing.T) {
	// Text-to-speech with explicit MP3 response format
	var req pkg.CreateSpeechRequest
	if err := json.Unmarshal([]byte(`{"input":"The quick brown fox jumps over the lazy dog.","model":"tts-1-hd","response_format":"mp3","speed":1.0,"voice":"nova"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/smoke_speech_mp3_format"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Speech(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	value := result
	if len(value) == 0 {
		t.Errorf("expected non-empty value")
	}
}
