// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c095283619e1a6b5d39f2fca0101e20614d6d44ad3eaa97f8b9ef4aad6f928c4
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: list-models

use liter_llm::BatchClient;
use liter_llm::FileClient;
use liter_llm::LlmClient;
use liter_llm::ResponseClient;
mod common;
mod mock_server;
#[allow(unused_imports)]
use mock_server::{MockRoute, MockServer};

#[test]
fn test_empty_model_list() {
    common::runtime().block_on(async {
        // List models response returns an empty data array when no models are available
        let mock_route = MockRoute {
            path: "/models",
            method: "GET",
            status: 200,
            body: r#"{"data":[],"object":"list"}"#.to_string(),
            is_streaming: false,
            stream_chunks: vec![],
            headers: vec![],
            delay_ms: None,
        };
        let mock_server = MockServer::start(vec![mock_route]).await;
        let client =
            liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
        let result = client.list_models().await.expect("call failed");
        assert_eq!(
            result.data.len(),
            0,
            "expected exactly 0 elements, got {}",
            result.data.len()
        );
    });
}

#[test]
fn test_list_models_error_401() {
    common::runtime().block_on(async {
    // 401 Unauthorized error on list models request when API key is invalid
    let mock_route = MockRoute {
        path: "/models",
        method: "GET",
        status: 401,
        body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let client = liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.list_models().await;
    assert!(result.is_err(), "expected call to fail");
    { let __e = result.as_ref().err().unwrap(); assert!(format!("{:?}", __e).contains("Authentication") || __e.to_string().contains("Authentication"), "error message mismatch"); }
    assert_eq!({ let __err = result.as_ref().err().unwrap(); __err.status_code() }, 401, "equals assertion failed");
    });
}

#[test]
fn test_list_models_error_500() {
    common::runtime().block_on(async {
        // 500 Internal Server Error when listing models due to server failure
        let mock_route = MockRoute {
            path: "/models",
            method: "GET",
            status: 500,
            body: r#"{"error":{"code":"internal_error","message":"Internal server error","type":"server_error"}}"#
                .to_string(),
            is_streaming: false,
            stream_chunks: vec![],
            headers: vec![],
            delay_ms: None,
        };
        let mock_server = MockServer::start(vec![mock_route]).await;
        let client =
            liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
        let result = client.list_models().await;
        assert!(result.is_err(), "expected call to fail");
        {
            let __e = result.as_ref().err().unwrap();
            assert!(
                format!("{:?}", __e).contains("ServerError") || __e.to_string().contains("ServerError"),
                "error message mismatch"
            );
        }
        assert_eq!(
            {
                let __err = result.as_ref().err().unwrap();
                __err.status_code()
            },
            500,
            "equals assertion failed"
        );
    });
}

#[test]
fn test_list_models_filtered() {
    common::runtime().block_on(async {
    // List models response with multiple model objects
    let mock_route = MockRoute {
        path: "/models",
        method: "GET",
        status: 200,
        body: r#"{"data":[{"created":1687882411,"id":"gpt-4","object":"model","owned_by":"openai"},{"created":1677649963,"id":"gpt-3.5-turbo","object":"model","owned_by":"openai"},{"created":1694463867,"id":"text-embedding-3-small","object":"model","owned_by":"openai"},{"created":1698785189,"id":"dall-e-3","object":"model","owned_by":"openai"},{"created":1677532384,"id":"whisper-1","object":"model","owned_by":"openai"},{"created":1681767283,"id":"tts-1","object":"model","owned_by":"openai"}],"object":"list"}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let client = liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.list_models().await.expect("call failed");
    assert!(result.data.len() >= 5, "expected at least 5 elements, got {}", result.data.len());
    assert_eq!(result.data[0].object.to_string(), r#"model"#, "equals assertion failed");
    });
}
