<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f13dda4de0cb0d644313822ddeb49ff853d8a09e6f193b83b07298f6c656a48
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\CreateFileRequest;

/** E2e tests for category: files. */
final class FilesTest extends TestCase
{


    /** List files when no files have been uploaded */
    public function test_edge_file_empty_list(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_file_empty_list');
        $result = $client->listFiles();
        $data = $result->getData();

            $this->assertCount(0, $data);


    }


    /** Upload a large file successfully */
    public function test_edge_file_large_upload(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_file_large_upload');
        $req = \Liter\Llm\CreateFileRequest::from_json(json_encode(["file" => "eyJwcm9tcHQiOiAibGFyZ2UgdHJhaW5pbmcgZGF0YSJ9Cg==", "filename" => "large_training_data.jsonl", "purpose" => "fine-tune"]));
        $result = $client->createFile($req);

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');


    }


    /** 401 Unauthorized when listing files with invalid API key */
    public function test_error_file_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_file_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->listFiles();
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request when uploading a file with invalid purpose */
    public function test_error_file_bad_purpose(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_file_bad_purpose');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateFileRequest::from_json(json_encode(["file" => "data.jsonl", "purpose" => "invalid-purpose"]));
        $client->createFile($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 404 Not Found when retrieving a nonexistent file */
    public function test_error_file_not_found(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_file_not_found');
        // skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $client->retrieveFile("file-nonexistent");
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Upload a file for use with the API */
    public function test_smoke_create_file(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_create_file');
        $req = \Liter\Llm\CreateFileRequest::from_json(json_encode(["file" => "eyJwcm9tcHQiOiAiaGVsbG8ifQo=", "filename" => "training_data.jsonl", "purpose" => "fine-tune"]));
        $result = $client->createFile($req);

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');


    }


    /** Delete an uploaded file */
    public function test_smoke_delete_file(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_delete_file');
        $result = $client->deleteFile("file-abc123");

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');
            $this->assertEquals(true, $result->deleted);


    }


    /** Retrieve the content of an uploaded file */
    public function test_smoke_file_content(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_file_content');
        $result = $client->fileContent("file-abc123");

            $this->assertNotSame('', $result ?? '', 'expected non-empty value');


    }


    /** List all uploaded files */
    public function test_smoke_list_files(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_list_files');
        $result = $client->listFiles();
        $data = $result->getData();

            $this->assertCount(2, $data);


    }


    /** Retrieve metadata for an uploaded file */
    public function test_smoke_retrieve_file(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_retrieve_file');
        $result = $client->retrieveFile("file-abc123");

            $this->assertNotSame('', $result->id ?? '', 'expected non-empty value');


    }

}
