<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6a743bac3282b2d9bef97e7c36e7b453aa2a60472eab5e52779850e3ff7c8d16
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\CreateImageRequest;

/** E2e tests for category: image-generate. */
final class ImageGenerateTest extends TestCase
{


    /** Image generation returning base64-encoded data instead of URL */
    public function test_edge_image_b64_response(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_image_b64_response');
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A blue circle", "responseFormat" => "b64_json", "size" => "1024x1024"]));
        $result = $client->imageGenerate($req);
        $data = $result->getData();

            $this->assertCount(1, $data);
            $this->assertNotSame('', ($result->getData()[0]->b64Json ?? null) ?? '', 'expected non-empty value');


    }


    /** Image generation with an empty prompt returns 400 */
    public function test_edge_image_empty_prompt(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_image_empty_prompt');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "", "size" => "1024x1024"]));
        $client->imageGenerate($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Image generation requesting multiple images with n=3 */
    public function test_edge_image_multiple_n(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_image_multiple_n');
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 3, "prompt" => "A cat"]));
        $result = $client->imageGenerate($req);
        $data = $result->getData();

            $this->assertCount(3, $data);
            $this->assertNotSame('', ($result->getData()[0]->url ?? null) ?? '', 'expected non-empty value');
            $this->assertNotSame('', ($result->getData()[1]->url ?? null) ?? '', 'expected non-empty value');
            $this->assertNotSame('', ($result->getData()[2]->url ?? null) ?? '', 'expected non-empty value');


    }


    /** 401 Unauthorized when generating images with invalid API key */
    public function test_error_image_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_image_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A cat", "size" => "1024x1024"]));
        $client->imageGenerate($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request when image generation parameters are invalid */
    public function test_error_image_bad_request(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_image_bad_request');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A cat", "size" => "9999x9999"]));
        $client->imageGenerate($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 429 Rate limit exceeded for image generation */
    public function test_error_image_rate_limit(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_image_rate_limit');
        // skipped: declared error variant 'RateLimited' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A cat", "size" => "1024x1024"]));
        $client->imageGenerate($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Basic image generation with a text prompt */
    public function test_smoke_image_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_image_basic');
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A white cat sitting on a windowsill", "size" => "1024x1024"]));
        $result = $client->imageGenerate($req);
        $data = $result->getData();

            $this->assertCount(1, $data);
            $this->assertNotSame('', ($result->getData()[0]->url ?? null) ?? '', 'expected non-empty value');


    }


    /** Image generation requesting multiple images */
    public function test_smoke_image_multiple(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_image_multiple');
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-2", "n" => 3, "prompt" => "A red bicycle", "size" => "256x256"]));
        $result = $client->imageGenerate($req);
        $data = $result->getData();

            $this->assertCount(3, $data);
            $this->assertNotSame('', ($result->getData()[0]->url ?? null) ?? '', 'expected non-empty value');


    }


    /** Image generation with explicit size parameter */
    public function test_smoke_image_with_size(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_image_with_size');
        $req = \Liter\Llm\CreateImageRequest::from_json(json_encode(["model" => "dall-e-3", "n" => 1, "prompt" => "A sunset over mountains", "size" => "1792x1024"]));
        $result = $client->imageGenerate($req);
        $data = $result->getData();

            $this->assertCount(1, $data);
            $this->assertNotSame('', ($result->getData()[0]->url ?? null) ?? '', 'expected non-empty value');


    }

}
