<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:95398be68677488d8115cc676520074524510e0ae3d0f41b94c8b4bb22cecfce
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\OcrRequest;

/** E2e tests for category: ocr. */
final class OcrTest extends TestCase
{


    /** 400 Bad Request error when OCR input has an invalid image format */
    public function test_ocr_error_400(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/ocr_error_400');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\OcrRequest::from_json(json_encode(["document" => ["type" => "document_url", "url" => "invalid://url"], "model" => "mistral/mistral-ocr-latest"]));
        $client->ocr($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 401 Unauthorized error on OCR request due to invalid API credentials */
    public function test_ocr_error_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/ocr_error_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\OcrRequest::from_json(json_encode(["document" => ["type" => "document_url", "url" => "https://example.com/doc.pdf"], "model" => "mistral/mistral-ocr-latest"]));
        $client->ocr($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** OCR request returning multiple pages of document content */
    public function test_ocr_multi_page(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/ocr_multi_page');
        $req = \Liter\Llm\OcrRequest::from_json(json_encode(["document" => ["type" => "document_url", "url" => "https://example.com/multipage.pdf"], "model" => "mistral/mistral-ocr-latest"]));
        $result = $client->ocr($req);
        $pages = $result->getPages();

            $this->assertCount(2, $pages);
            $this->assertEquals(0, $result->getPages()[0]->index);
            $this->assertEquals(1, $result->getPages()[1]->index);


    }


    /** OCR request with a document URL input */
    public function test_ocr_url_document(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/ocr_url_document');
        $req = \Liter\Llm\OcrRequest::from_json(json_encode(["document" => ["type" => "document_url", "url" => "https://example.com/doc.pdf"], "model" => "mistral/mistral-ocr-latest"]));
        $result = $client->ocr($req);

        $this->assertNotNull($result);


    }

}
