<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f36306a4ec5831f558031552574f2f5e374b2034309009a4565b4e68364779b1
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\SearchRequest;

/** E2e tests for category: search. */
final class SearchTest extends TestCase
{


    /** Basic web search request with a simple query */
    public function test_search_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_basic');
        $req = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "What is Rust programming language?"]));
        $result = $client->search($req);

        $this->assertNotNull($result);


    }


    /** Web search with a query that returns no results */
    public function test_search_empty_results(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_empty_results');
        $req = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "xyznonexistent12345xyz"]));
        $result = $client->search($req);

        $this->assertNotNull($result);


    }


    /** 400 Bad Request error when search query is empty */
    public function test_search_error_400(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_error_400');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => ""]));
        $client->search($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 401 Unauthorized error on web search due to invalid API credentials */
    public function test_search_error_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_error_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "test"]));
        $client->search($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Search request with max_results parameter limiting response count */
    public function test_search_with_max_results(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_with_max_results');
        $req = \Liter\Llm\SearchRequest::from_json(json_encode(["maxResults" => 2, "model" => "brave/web-search", "query" => "Rust programming"]));
        $result = $client->search($req);
        $results = $result->getResults();

            $this->assertCount(2, $results);


    }

}
