<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82a001c029db32e2e217c05da2854aa5aa03a489dc2b850003dba11bba4d4d87
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\CreateSpeechRequest;

/** E2e tests for category: speech. */
final class SpeechTest extends TestCase
{


    /** Text-to-speech with specific voice selection */
    public function test_edge_speech_all_voices(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_speech_all_voices');
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "Hello world", "model" => "tts-1", "voice" => "nova"]));
        $result = $client->speech($req);

            $this->assertNotSame('', $result ?? '', 'expected non-empty value');


    }


    /** Speech generation with a very long input text */
    public function test_edge_speech_long_input(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_speech_long_input');
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.", "model" => "tts-1", "voice" => "echo"]));
        $result = $client->speech($req);

            $this->assertNotSame('', $result ?? '', 'expected non-empty value');


    }


    /** 401 Unauthorized for speech generation with invalid API key */
    public function test_error_speech_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_speech_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "Hello", "model" => "tts-1", "voice" => "alloy"]));
        $client->speech($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request for speech with unsupported model */
    public function test_error_speech_bad_model(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_speech_bad_model');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "Hello", "model" => "tts-nonexistent", "voice" => "alloy"]));
        $client->speech($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Basic text-to-speech generation */
    public function test_smoke_speech_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_speech_basic');
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "Hello, world!", "model" => "tts-1", "voice" => "alloy"]));
        $result = $client->speech($req);

            $this->assertNotSame('', $result ?? '', 'expected non-empty value');


    }


    /** Text-to-speech with explicit MP3 response format */
    public function test_smoke_speech_mp3_format(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_speech_mp3_format');
        $req = \Liter\Llm\CreateSpeechRequest::from_json(json_encode(["input" => "The quick brown fox jumps over the lazy dog.", "model" => "tts-1-hd", "responseFormat" => "mp3", "speed" => 1.0, "voice" => "nova"]));
        $result = $client->speech($req);

            $this->assertNotSame('', $result ?? '', 'expected non-empty value');


    }

}
