<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7807be201a2ae8acbb7b2c21ef786b56aca7a8e65d29bf1598d4ee15c90e2c89
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\CreateTranscriptionRequest;

/** E2e tests for category: transcribe. */
final class TranscribeTest extends TestCase
{


    /** Transcription of a silent or empty audio file returns empty text */
    public function test_edge_transcribe_empty_audio(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_transcribe_empty_audio');
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "silence.mp3", "model" => "whisper-1"]));
        $result = $client->transcribe($req);

            $this->assertStringContainsString("", $result->text);


    }


    /** Transcription with verbose JSON response format including timestamp segments */
    public function test_edge_transcribe_with_timestamps(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/edge_transcribe_with_timestamps');
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "audio.mp3", "model" => "whisper-1", "responseFormat" => "verbose_json"]));
        $result = $client->transcribe($req);
        $segments = $result->getSegments();

            $this->assertNotSame('', $result->text ?? '', 'expected non-empty value');
            $this->assertCount(3, $segments);
            $this->assertEquals(0, $result->getSegments()[0]->id);


    }


    /** 401 Unauthorized for transcription with invalid API key */
    public function test_error_transcribe_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_transcribe_auth_401');
        // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "audio.mp3", "model" => "whisper-1"]));
        $client->transcribe($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** 400 Bad Request when audio format is unsupported */
    public function test_error_transcribe_bad_format(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/error_transcribe_bad_format');
        // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        $this->expectException(\Exception::class);
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "audio.xyz", "model" => "whisper-1"]));
        $client->transcribe($req);
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

    }


    /** Basic audio transcription */
    public function test_smoke_transcribe_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_transcribe_basic');
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "audio.mp3", "model" => "whisper-1"]));
        $result = $client->transcribe($req);

            $this->assertStringContainsString("Hello, this is a test transcription.", $result->text);


    }


    /** Audio transcription with explicit language hint */
    public function test_smoke_transcribe_with_language(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/smoke_transcribe_with_language');
        $req = \Liter\Llm\CreateTranscriptionRequest::from_json(json_encode(["file" => "audio_de.mp3", "language" => "de", "model" => "whisper-1"]));
        $result = $client->transcribe($req);

            $this->assertStringContainsString("Hallo, dies ist ein Testtranskription.", $result->text);


    }

}
