// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ddc4a03131ea14c80ee313e5843a15e77dff34b099a70bbfd92207af4849d693
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient } from "@xberg-io/liter-llm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("search", () => {

	it("search_basic: Basic web search request with a simple query", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/search_basic`);
		const result = await client.search({ model: "brave/web-search", query: "What is Rust programming language?" });
    expect(result).toBeDefined();

	}, 30000);

	it("search_empty_results: Web search with a query that returns no results", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/search_empty_results`);
		const result = await client.search({ model: "brave/web-search", query: "xyznonexistent12345xyz" });
    expect(result).toBeDefined();

	}, 30000);

	it("search_error_400: 400 Bad Request error when search query is empty", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/search_error_400`);
		await expect(async () => {
			await client.search({ model: "brave/web-search", query: "" });
		}).rejects.toThrow();
		// skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("search_error_401: 401 Unauthorized error on web search due to invalid API credentials", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/search_error_401`);
		await expect(async () => {
			await client.search({ model: "brave/web-search", query: "test" });
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("search_with_max_results: Search request with max_results parameter limiting response count", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/search_with_max_results`);
		const result = await client.search({ maxResults: 2, model: "brave/web-search", query: "Rust programming" });
    expect(result.results.length).toBe(2);

	}, 30000);

});
