// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e3d19b06217ae21699d4af35c2fddd6e5b83aa4cf0c173982c56f47bb878880b
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, ToolType, type Message } from "@xberg-io/liter-llm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("streaming", () => {

	it("anthropic_stream: Streaming chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) yielding multiple SSE chunks", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/anthropic_stream`);
		const stream = await client.chatStream({ maxTokens: 32, messages: [{ role: "user", user: { content: "Count to three, one word per response." } } as Message], model: "anthropic/claude-3-5-sonnet-20241022", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(3);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("One Two Three");
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);

	}, 30000);

	it("azure_stream: Streaming chat completion via Azure OpenAI — verifies the azure/ prefix routes correctly and SSE chunks are delivered in the standard OpenAI chat.completion.chunk shape", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/azure_stream`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Count to 3" } } as Message], model: "azure/gpt-4", stream: true, temperature: 0 });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(3);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("1 2 3");
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);

	}, 30000);

	it("basic_stream: Streaming chat completion that produces content across multiple SSE chunks", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/basic_stream`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Count to 3" } } as Message], model: "gpt-4", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(3);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("1 2 3");

	}, 30000);

	it("bedrock_stream: Streaming chat completion via the AWS Bedrock provider using the bedrock/ prefix — verifies SSE chunks are yielded and assembled correctly from the Converse streaming API", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/bedrock_stream`);
		const stream = await client.chatStream({ maxTokens: 32, messages: [{ role: "user", user: { content: "Count to three, one word per response." } } as Message], model: "bedrock/anthropic.claude-3-sonnet-20240229-v1:0", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(2);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("One Two Three");
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);

	}, 30000);

	it("edge_stream_function_call: Streaming chat completion with tool/function call chunks", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_stream_function_call`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "What's the weather?" } } as Message], model: "gpt-4", tools: [{ function: { name: "get_weather", parameters: { properties: { city: { type: "string" } }, type: "object" } }, toolType: ToolType.Function }] });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(2);
    expect(chunks).toBeDefined();

	}, 30000);

	it("empty_stream: Streaming chat completion that produces no content chunks before the DONE signal", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/empty_stream`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Say nothing" } } as Message], model: "gpt-4", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(0);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("");

	}, 30000);

	it("local_stream_ollama: Streaming chat completion via Ollama local provider with SSE chunks", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/local_stream_ollama`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Count to 3" } } as Message], model: "ollama/qwen2:0.5b", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks).toBeDefined();
    expect(chunks.length).toBeGreaterThanOrEqual(3);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("1 2 3");
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);

	}, 30000);

	it("stream_content_policy_error: 400 Bad Request error on stream due to content policy violation", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stream_content_policy_error`);
		await expect(async () => {
			const _stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Generate harmful content" } } as Message], model: "gpt-4o", stream: true });
			for await (const _ of _stream) {
				/* drain to surface HTTP errors */
			}
		}).rejects.toThrow();
		// skipped: declared error variant 'ContentPolicy' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("stream_done_signal: Verify that the [DONE] sentinel signal properly terminates the stream", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stream_done_signal`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Say done" } } as Message], model: "gpt-4", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("Done");
    expect(true).toBe(true);

	}, 30000);

	it("stream_error_401: 401 Unauthorized error on stream initiation before any chunks are received", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stream_error_401`);
		await expect(async () => {
			const _stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Hello" } } as Message], model: "gpt-4", stream: true });
			for await (const _ of _stream) {
				/* drain to surface HTTP errors */
			}
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("stream_multiple_choices: Streaming chat completion with multiple choice outputs (n > 1)", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stream_multiple_choices`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "Hello" } } as Message], model: "gpt-4o", n: 2, stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks).toBeDefined();

	}, 30000);

	it("stream_with_tool_calls: Streaming chat completion where the assistant responds with a tool call across multiple chunks", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stream_with_tool_calls`);
		const stream = await client.chatStream({ messages: [{ role: "user", user: { content: "What is the weather in NYC?" } } as Message], model: "gpt-4", stream: true, tools: [{ function: { description: "Get the current weather for a given location", name: "get_weather", parameters: { properties: { location: { description: "The city and state, e.g. New York, NY", type: "string" } }, required: ["location"], type: "object" } }, toolType: ToolType.Function }] });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(4);
    expect(chunks.length > 0 ? chunks[chunks.length - 1].choices?.[0]?.finishReason : undefined).toBe("tool_calls");
    {
        const _v = chunks.flatMap((c: any) => c.choices?.[0]?.delta?.toolCalls ?? []);
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect((chunks.flatMap((c: any) => c.choices?.[0]?.delta?.toolCalls ?? []))[0].function.name).toBe("get_weather");

	}, 30000);

	it("vertex_stream: Streaming chat completion via the Google Vertex AI provider using the vertex_ai/ prefix — verifies SSE chunks from the Gemini streaming endpoint are yielded and assembled correctly", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/vertex_stream`);
		const stream = await client.chatStream({ maxTokens: 32, messages: [{ role: "user", user: { content: "Count to three, one word per response." } } as Message], model: "vertex_ai/gemini-2.0-flash", stream: true });
		const chunks: any[] = [];
    for await (const _chunk of stream) { chunks.push(_chunk); }
    expect(chunks.length).toBeGreaterThanOrEqual(2);
    expect(chunks.map((c: any) => c.choices?.[0]?.delta?.content ?? '').join('')).toBe("One Two Three");
    expect(chunks.length > 0 && chunks[chunks.length - 1].choices?.[0]?.finishReason != null).toBe(true);

	}, 30000);

});
