// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b244c071584cde8bc2450fc06a3b1ee9b70a3b2d8bfc5db3cbbc15275037ab74
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: contract.
final class ContractTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testBindingApiParity() async throws {
        // Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Contract test\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/binding_api_parity")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_125e9ea6_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_125e9ea6_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "OK")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.usage()?.totalTokens(), 6)
        XCTAssertEqual(result.model().toString(), "gpt-4o")
    }

    func testContractOcr() async throws {
        // Verify ocr() method exists in all bindings
        let _req = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/contract-test.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/contract_ocr")
        do {
            _ = try await _client.ocr(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

    func testContractSearch() async throws {
        // Verify search() method exists in all bindings
        let _req = try LiterLlm.searchRequestFromJson("{\"model\":\"brave/web-search\",\"query\":\"contract test query\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/contract_search")
        do {
            _ = try await _client.search(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

}
