// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f2cca771a7684c9ba4dd23eeecee8999fc1dd7e920c55d94d0d6e7ad55671b2a
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: custom_provider.
final class CustomProviderTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testProviderAuth() async throws {
        // Tests custom provider with custom auth header
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/provider_auth")
        do {
            _ = try await _client.chat(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

    func testRegisterProvider() async throws {
        // Tests that a custom provider can be registered and routes requests
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/register_provider")
        do {
            _ = try await _client.chat(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

}
