// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0334a9db25ebacbd432f604561accfd43dfc7aaa18ac0cd52f6007acfa7c10a6
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: moderate.
final class ModerateTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testEdgeModerateAllCategories() async throws {
        // Moderation response with multiple categories flagged
        let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"Extremely harmful content targeting multiple categories\",\"model\":\"omni-moderation-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_moderate_all_categories")
        let result = try await _client.moderate(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 1)
        XCTAssertEqual(result.results[0].flagged, true)
    }

    func testEdgeModerateEmptyInput() async throws {
        // Moderation with empty string input
        let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"\",\"model\":\"omni-moderation-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_moderate_empty_input")
        let result = try await _client.moderate(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 1)
        XCTAssertEqual(result.results[0].flagged, false)
    }

    func testErrorModerateAuth401() async throws {
        // 401 Unauthorized for moderation with invalid API key
        do {
            let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"Hello\",\"model\":\"omni-moderation-latest\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_moderate_auth_401")
            _ = try await _client.moderate(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testErrorModerateBadRequest() async throws {
        // 400 Bad Request for moderation with invalid model
        do {
            let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"Hello\",\"model\":\"nonexistent-moderation\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_moderate_bad_request")
            _ = try await _client.moderate(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSmokeModerateBatch() async throws {
        // Moderate multiple inputs in a single request
        let _req = try LiterLlm.moderationRequestFromJson("{\"input\":[\"Hello world\",\"Nice weather today\"],\"model\":\"omni-moderation-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_moderate_batch")
        let result = try await _client.moderate(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 2)
        XCTAssertEqual(result.results[0].flagged, false)
    }

    func testSmokeModerateFlagged() async throws {
        // Moderation detects flagged content
        let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"I want to hurt someone very badly\",\"model\":\"omni-moderation-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_moderate_flagged")
        let result = try await _client.moderate(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 1)
        XCTAssertEqual(result.results[0].flagged, true)
    }

    func testSmokeModerateSingle() async throws {
        // Moderate a single non-flagged input
        let _req = try LiterLlm.moderationRequestFromJson("{\"input\":\"The weather is nice today.\",\"model\":\"omni-moderation-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_moderate_single")
        let result = try await _client.moderate(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 1)
        XCTAssertEqual(result.results[0].flagged, false)
    }

}
