// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:306623f91c117191fc6aad7298d57fbd5bf69ea9f2d889b7d8370968585e6c83
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: ocr.
final class OcrTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testOcrError400() async throws {
        // 400 Bad Request error when OCR input has an invalid image format
        do {
            let _req = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"invalid://url\"},\"model\":\"mistral/mistral-ocr-latest\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_error_400")
            _ = try await _client.ocr(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testOcrError401() async throws {
        // 401 Unauthorized error on OCR request due to invalid API credentials
        do {
            let _req = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/doc.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_error_401")
            _ = try await _client.ocr(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testOcrMultiPage() async throws {
        // OCR request returning multiple pages of document content
        let _req = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/multipage.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_multi_page")
        let result = try await _client.ocr(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.pages.count, 2)
        XCTAssertEqual(result.pages[0].index, 0)
        XCTAssertEqual(result.pages[1].index, 1)
    }

    func testOcrUrlDocument() async throws {
        // OCR request with a document URL input
        let _req = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/doc.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_url_document")
        do {
            _ = try await _client.ocr(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

}
