// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9dad9e17872420e544cab74271c4d7267ce46ff1c5b5af8affd18f6a80cd05f
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: parity.
final class ParityTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testApiSurfaceParity() async throws {
        // Canonical API surface definition for cross-binding parity verification
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/api_surface_parity")
        do {
            _ = try await _client.chat(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

}
