// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5808a102f0e3c5c716ab4d0b82c5e47de271f35eb19f76c28970586727b554fe
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testAnthropicChat() async throws {
        // Basic chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) with system and user messages
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":16,\"messages\":[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"Say hello in one word.\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/anthropic_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "claude-3-5-sonnet-20241022")
        XCTAssertEqual(result.usage()?.totalTokens(), 23)
    }

    func testAzureChat() async throws {
        // Chat completion via Azure OpenAI with the azure/ prefix for provider routing — verifies the prefix is stripped before dispatching and the response is normalised to the standard OpenAI chat completion shape
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":16,\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"azure/gpt-4\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/azure_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "gpt-4")
        XCTAssertEqual(result.usage()?.totalTokens(), 13)
    }

    func testAzureEmbed() async throws {
        // Embedding request via Azure OpenAI using the azure/ provider prefix — response follows the standard OpenAI embeddings shape that Azure returns unchanged
        let _req = try LiterLlm.embeddingRequestFromJson("{\"input\":\"Hello world\",\"model\":\"azure/text-embedding-ada-002\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/azure_embed")
        let result = try await _client.embed(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.data.count, 1)
        XCTAssertEqual(result.data[0].embedding.count, 1480)
    }

    func testBasicChat() async throws {
        // Basic chat completion with a single user message
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/basic_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.usage()?.totalTokens(), 15)
        XCTAssertEqual(result.model().toString(), "gpt-4")
    }

    func testBasicEmbed() async throws {
        // Basic embedding request for a single input string
        let _req = try LiterLlm.embeddingRequestFromJson("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/basic_embed")
        let result = try await _client.embed(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.data.count, 1)
        XCTAssertEqual(result.data[0].embedding.count, 5)
    }

    func testBasicListModels() async throws {
        // List available models from the API
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/basic_list_models")
        let result = try await _client.listModels()
        // not_error: covered by try propagation
        XCTAssertGreaterThanOrEqual(result.data.count, 1)
    }

    func testBedrockChat() async throws {
        // Basic chat completion via the AWS Bedrock provider using the bedrock/ prefix for routing — verifies the prefix is stripped before dispatching and the Converse API response is normalised to the standard OpenAI chat completion shape
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":16,\"messages\":[{\"content\":\"Say hello in one word.\",\"role\":\"user\"}],\"model\":\"bedrock/anthropic.claude-3-sonnet-20240229-v1:0\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/bedrock_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "anthropic.claude-3-sonnet-20240229-v1:0")
        XCTAssertEqual(result.usage()?.totalTokens(), 15)
    }

    func testGithubCopilotChat() async throws {
        // Basic chat completion via the GitHub Copilot provider (gpt-4o) with a single user message
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":16,\"messages\":[{\"content\":\"Say hello in one word.\",\"role\":\"user\"}],\"model\":\"github_copilot/gpt-4o\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/github_copilot_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "gpt-4o")
        XCTAssertEqual(result.usage()?.totalTokens(), 14)
    }

    func testSmokeCacheMemory() async throws {
        // Test in-memory caching by sending identical requests twice
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":5,\"messages\":[{\"content\":\"What is 2+2? Answer with just the number.\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o-mini\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_cache_memory")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.choices().isEmpty, "expected non-empty value")
        // not_error: covered by try propagation
    }

    func testSmokeChatAnthropic() async throws {
        // Basic chat completion against real Anthropic API
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":10,\"messages\":[{\"content\":\"Say hello in exactly one word.\",\"role\":\"user\"}],\"model\":\"anthropic/claude-sonnet-4-20250514\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_chat_anthropic")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.choices().isEmpty, "expected non-empty value")
        XCTAssertTrue(result.usage() != nil, "expected non-empty value")
    }

    func testSmokeChatGemini() async throws {
        // Basic chat completion against real Google Gemini API
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":10,\"messages\":[{\"content\":\"Say hello in exactly one word.\",\"role\":\"user\"}],\"model\":\"gemini/gemini-2.5-flash-lite\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_chat_gemini")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.choices().isEmpty, "expected non-empty value")
        XCTAssertTrue(result.usage() != nil, "expected non-empty value")
    }

    func testSmokeChatOpenai() async throws {
        // Basic chat completion against real OpenAI API
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":10,\"messages\":[{\"content\":\"Say hello in exactly one word.\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o-mini\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_chat_openai")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.choices().isEmpty, "expected non-empty value")
        XCTAssertTrue(result.usage() != nil, "expected non-empty value")
    }

    func testSmokeEmbedOpenai() async throws {
        // Embeddings request against real OpenAI API
        let _req = try LiterLlm.embeddingRequestFromJson("{\"input\":[\"Hello world\"],\"model\":\"openai/text-embedding-3-small\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_embed_openai")
        let result = try await _client.embed(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.data.isEmpty, "expected non-empty value")
    }

    func testSmokeListModelsOpenai() async throws {
        // List models against real OpenAI API
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_list_models_openai")
        let result = try await _client.listModels()
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertGreaterThanOrEqual(result.data.count, 1)
    }

    func testSmokeProviderRouting() async throws {
        // Test provider routing by sending requests to OpenAI and Anthropic
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":5,\"messages\":[{\"content\":\"Say hi.\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o-mini\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_provider_routing")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertTrue(!result.choices().isEmpty, "expected non-empty value")
        // not_error: covered by try propagation
    }

    func testSmokeStreamingOpenai() async throws {
        // Chat streaming against real OpenAI API, verifies chunks received
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":50,\"messages\":[{\"content\":\"Count from 1 to 5.\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o-mini\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_streaming_openai")
        let result = try await _client.chatStream(_req)
        var chunks: [LiterLlm.ChatCompletionChunk] = []
                for try await _chunk in result { chunks.append(_chunk) }
        // not_error: covered by try propagation
        // not_error: covered by try propagation
        XCTAssertGreaterThanOrEqual(chunks.count, 1)
    }

    func testVertexChat() async throws {
        // Basic chat completion via the Google Vertex AI provider using the vertex_ai/ prefix for routing — verifies the prefix is stripped before dispatching and the Gemini response is normalised to the standard OpenAI chat completion shape
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":16,\"messages\":[{\"content\":\"Say hello in one word.\",\"role\":\"user\"}],\"model\":\"vertex_ai/gemini-2.0-flash\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/vertex_chat")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_8313c4be_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_8313c4be_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "Hello!")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "gemini-2.0-flash")
        XCTAssertEqual(result.usage()?.totalTokens(), 13)
    }

    func testVertexEmbed() async throws {
        // Embedding request via Google Vertex AI using the vertex_ai/ provider prefix and the text-embedding-005 model — response follows the standard OpenAI embeddings shape
        let _req = try LiterLlm.embeddingRequestFromJson("{\"input\":\"Hello\",\"model\":\"vertex_ai/text-embedding-005\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/vertex_embed")
        let result = try await _client.embed(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.data.count, 1)
        XCTAssertEqual(result.data[0].embedding.count, 160)
    }

}
