// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:022e602094e88810918241ae09f8e5f5dd17a0c7eaf5e5c3a94ff4f23969b632
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: speech.
final class SpeechTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testEdgeSpeechAllVoices() async throws {
        // Text-to-speech with specific voice selection
        let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"Hello world\",\"model\":\"tts-1\",\"voice\":\"nova\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_speech_all_voices")
        let result = try await _client.speech(_req)
        // not_error: covered by try propagation
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

    func testEdgeSpeechLongInput() async throws {
        // Speech generation with a very long input text
        let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.\",\"model\":\"tts-1\",\"voice\":\"echo\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_speech_long_input")
        let result = try await _client.speech(_req)
        // not_error: covered by try propagation
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

    func testErrorSpeechAuth401() async throws {
        // 401 Unauthorized for speech generation with invalid API key
        do {
            let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"Hello\",\"model\":\"tts-1\",\"voice\":\"alloy\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_speech_auth_401")
            _ = try await _client.speech(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testErrorSpeechBadModel() async throws {
        // 400 Bad Request for speech with unsupported model
        do {
            let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"Hello\",\"model\":\"tts-nonexistent\",\"voice\":\"alloy\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_speech_bad_model")
            _ = try await _client.speech(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSmokeSpeechBasic() async throws {
        // Basic text-to-speech generation
        let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"Hello, world!\",\"model\":\"tts-1\",\"voice\":\"alloy\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_speech_basic")
        let result = try await _client.speech(_req)
        // not_error: covered by try propagation
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

    func testSmokeSpeechMp3Format() async throws {
        // Text-to-speech with explicit MP3 response format
        let _req = try LiterLlm.createSpeechRequestFromJson("{\"input\":\"The quick brown fox jumps over the lazy dog.\",\"model\":\"tts-1-hd\",\"response_format\":\"mp3\",\"speed\":1.0,\"voice\":\"nova\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_speech_mp3_format")
        let result = try await _client.speech(_req)
        // not_error: covered by try propagation
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

}
