# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:865736b07c9fba412417b622cee88dde579ef871a7b2e00d7ff2eb411037e592
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "2.0.0"
end
