# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:991b0aedfb545bdab037f9e530924581f5e24e40ce1bbdcfadd66b70bea6313f
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "1.19.3"
end
