// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0d8411bd5899e7e87e1a96f9c5d570fd007562eae3fd0fbf6a616aaf7e0a67c6
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.ChatCompletionRequest

/** E2e tests for category: configuration. */
class ConfigurationTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testCustomBaseUrl(): Unit = runBlocking {
        // Client configured with a custom base URL routes all requests to that endpoint
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"local-model\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.custom_base_url", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/custom_base_url"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertEquals("local-model", result.model)
        client.close()
    }

    @Test
    fun testExtraHeaders(): Unit = runBlocking {
        // Client configured with extra custom headers successfully completes a chat request
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.extra_headers", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/extra_headers"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testLocalProviderLlamacpp(): Unit = runBlocking {
        // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"llamacpp/my-model\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.local_provider_llamacpp", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/local_provider_llamacpp"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertEquals("my-model", result.model)
        client.close()
    }

    @Test
    fun testLocalProviderOllama(): Unit = runBlocking {
        // Ollama local provider routes requests via ollama/ model prefix with no auth
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"ollama/qwen2:0.5b\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.local_provider_ollama", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/local_provider_ollama"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertEquals("qwen2:0.5b", result.model)
        client.close()
    }

    @Test
    fun testLocalProviderVllm(): Unit = runBlocking {
        // vLLM local provider routes requests via vllm/ model prefix with no auth
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"vllm/meta-llama/Llama-3.2-1B\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.local_provider_vllm", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/local_provider_vllm"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertEquals("meta-llama/Llama-3.2-1B", result.model)
        client.close()
    }

}
