// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fbf7c8ba5f540822728fb7494b46389502a369426abd80298b614c24975d9ae0
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.CreateImageRequest

/** E2e tests for category: image-generate. */
class ImageGenerateTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeImageB64Response(): Unit = runBlocking {
        // Image generation returning base64-encoded data instead of URL
        val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A blue circle\",\"response_format\":\"b64_json\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_image_b64_response", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_image_b64_response"))
        val result = client.imageGenerate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertTrue(result.data.first().b64Json != null, "expected non-empty value")
        client.close()
    }

    @Test
    fun testEdgeImageEmptyPrompt(): Unit = runBlocking {
        // Image generation with an empty prompt returns 400
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_image_empty_prompt", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_image_empty_prompt"))
            client.imageGenerate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testEdgeImageMultipleN(): Unit = runBlocking {
        // Image generation requesting multiple images with n=3
        val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":3,\"prompt\":\"A cat\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_image_multiple_n", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_image_multiple_n"))
        val result = client.imageGenerate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(3, result.data.size, "expected exactly 3 elements")
        assertTrue(result.data.first().url != null, "expected non-empty value")
        assertTrue(result.data.get(1).url != null, "expected non-empty value")
        assertTrue(result.data.get(2).url != null, "expected non-empty value")
        client.close()
    }

    @Test
    fun testErrorImageAuth401(): Unit = runBlocking {
        // 401 Unauthorized when generating images with invalid API key
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_image_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_image_auth_401"))
            client.imageGenerate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorImageBadRequest(): Unit = runBlocking {
        // 400 Bad Request when image generation parameters are invalid
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"9999x9999\"}", CreateImageRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_image_bad_request", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_image_bad_request"))
            client.imageGenerate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorImageRateLimit(): Unit = runBlocking {
        // 429 Rate limit exceeded for image generation
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_image_rate_limit", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_image_rate_limit"))
            client.imageGenerate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeImageBasic(): Unit = runBlocking {
        // Basic image generation with a text prompt
        val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A white cat sitting on a windowsill\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_image_basic", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_image_basic"))
        val result = client.imageGenerate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertTrue(result.data.first().url != null, "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeImageMultiple(): Unit = runBlocking {
        // Image generation requesting multiple images
        val req = MAPPER.readValue("{\"model\":\"dall-e-2\",\"n\":3,\"prompt\":\"A red bicycle\",\"size\":\"256x256\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_image_multiple", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_image_multiple"))
        val result = client.imageGenerate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(3, result.data.size, "expected exactly 3 elements")
        assertTrue(result.data.first().url != null, "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeImageWithSize(): Unit = runBlocking {
        // Image generation with explicit size parameter
        val req = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A sunset over mountains\",\"size\":\"1792x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_image_with_size", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_image_with_size"))
        val result = client.imageGenerate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertTrue(result.data.first().url != null, "expected non-empty value")
        client.close()
    }

}
