// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:deb32243dc679e74eb73bc589ce0348e18db94afdec499780d851fbc2920d6e1
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.RerankRequest

/** E2e tests for category: rerank. */
class RerankTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeRerankEmptyQuery(): Unit = runBlocking {
        // Reranking with an empty query string
        val req = MAPPER.readValue("{\"documents\":[\"Some document\",\"Another document\"],\"model\":\"rerank-v3.5\",\"query\":\"\"}", RerankRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_rerank_empty_query", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_rerank_empty_query"))
        val result = client.rerank(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        client.close()
    }

    @Test
    fun testEdgeRerankSingleDoc(): Unit = runBlocking {
        // Reranking with only a single document
        val req = MAPPER.readValue("{\"documents\":[\"Artificial intelligence is the simulation of human intelligence.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is AI?\"}", RerankRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_rerank_single_doc", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_rerank_single_doc"))
        val result = client.rerank(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertTrue(result.results.first().relevanceScore > 0.9, "expected > 0.9")
        client.close()
    }

    @Test
    fun testErrorRerankAuth401(): Unit = runBlocking {
        // 401 Unauthorized for reranking with invalid API key
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"documents\":[\"doc1\"],\"model\":\"rerank-v3.5\",\"query\":\"test\"}", RerankRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_rerank_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_rerank_auth_401"))
            client.rerank(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorRerankBadRequest(): Unit = runBlocking {
        // 400 Bad Request for reranking with invalid model
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"documents\":[\"doc1\"],\"model\":\"nonexistent-rerank\",\"query\":\"test\"}", RerankRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_rerank_bad_request", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_rerank_bad_request"))
            client.rerank(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeRerankBasic(): Unit = runBlocking {
        // Basic reranking of documents against a query
        val req = MAPPER.readValue("{\"documents\":[\"Machine learning is a subset of AI.\",\"The weather is sunny today.\",\"Deep learning uses neural networks.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is machine learning?\"}", RerankRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_rerank_basic", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_rerank_basic"))
        val result = client.rerank(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(3, result.results.size, "expected exactly 3 elements")
        assertTrue(result.results.first().relevanceScore > 0.9, "expected > 0.9")
        client.close()
    }

    @Test
    fun testSmokeRerankReturnDocs(): Unit = runBlocking {
        // Reranking with return_documents flag to include document text
        val req = MAPPER.readValue("{\"documents\":[\"Rust is a systems programming language.\",\"Iron rusts when exposed to water.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Rust?\",\"return_documents\":true}", RerankRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_rerank_return_docs", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_rerank_return_docs"))
        val result = client.rerank(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        assertTrue(result.results.first().document != null, "expected non-empty value")
        assertTrue(result.results.first().relevanceScore > 0.9, "expected > 0.9")
        client.close()
    }

    @Test
    fun testSmokeRerankWithTopN(): Unit = runBlocking {
        // Reranking with top_n parameter to limit results
        val req = MAPPER.readValue("{\"documents\":[\"Python is a programming language.\",\"Cats are cute animals.\",\"Python was created by Guido van Rossum.\",\"The sun is a star.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Python?\",\"top_n\":2}", RerankRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_rerank_with_top_n", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_rerank_with_top_n"))
        val result = client.rerank(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        assertTrue(result.results.first().relevanceScore > 0.9, "expected > 0.9")
        client.close()
    }

}
