// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dc9c0d67f101410544ee8e760962450db410a98b1107138ed879a2457652e598
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.SearchRequest

/** E2e tests for category: search. */
class SearchTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testSearchBasic(): Unit = runBlocking {
        // Basic web search request with a simple query
        val req = MAPPER.readValue("{\"model\":\"brave/web-search\",\"query\":\"What is Rust programming language?\"}", SearchRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.search_basic", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/search_basic"))
        val result = client.search(req)
        assertNotNull(result, "expected non-null result")
        client.close()
    }

    @Test
    fun testSearchEmptyResults(): Unit = runBlocking {
        // Web search with a query that returns no results
        val req = MAPPER.readValue("{\"model\":\"brave/web-search\",\"query\":\"xyznonexistent12345xyz\"}", SearchRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.search_empty_results", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/search_empty_results"))
        val result = client.search(req)
        assertNotNull(result, "expected non-null result")
        client.close()
    }

    @Test
    fun testSearchError400(): Unit = runBlocking {
        // 400 Bad Request error when search query is empty
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"brave/web-search\",\"query\":\"\"}", SearchRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.search_error_400", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/search_error_400"))
            client.search(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSearchError401(): Unit = runBlocking {
        // 401 Unauthorized error on web search due to invalid API credentials
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"model\":\"brave/web-search\",\"query\":\"test\"}", SearchRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.search_error_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/search_error_401"))
            client.search(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSearchWithMaxResults(): Unit = runBlocking {
        // Search request with max_results parameter limiting response count
        val req = MAPPER.readValue("{\"max_results\":2,\"model\":\"brave/web-search\",\"query\":\"Rust programming\"}", SearchRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.search_with_max_results", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/search_with_max_results"))
        val result = client.search(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        client.close()
    }

}
