// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e4822698ecd1124f1d8089968035e849fc34b8c647c129ec7f4a621c11472d3
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.ChatCompletionRequest

/** E2e tests for category: chat. */
class ChatTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testDeveloperMessage(): Unit = runBlocking {
        // Chat request that includes a developer role message alongside user messages
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"You are a coding assistant. Always respond with concise code examples.\",\"role\":\"developer\"},{\"content\":\"How do I reverse a string in Python?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.developer_message", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/developer_message"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testEdgeChatMaxTokens(): Unit = runBlocking {
        // Chat request with max_tokens=1 terminates with length finish_reason
        val req = MAPPER.readValue("{\"max_tokens\":1,\"messages\":[{\"content\":\"Write a story\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_chat_max_tokens", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_chat_max_tokens"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals("length", result.choices.first().finishReason?.toWire().orEmpty())
        assertTrue(result.choices.first().message.content?.text().orEmpty().isNotEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testEdgeChatSystemOnly(): Unit = runBlocking {
        // Chat request with system message and user message
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"You are a helpful and concise assistant\",\"role\":\"system\"},{\"content\":\"Hi\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_chat_system_only", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_chat_system_only"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertTrue(result.choices.first().message.content?.text().orEmpty().isNotEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testEdgeChatTemperatureZero(): Unit = runBlocking {
        // Chat request with temperature=0 for deterministic responses
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_chat_temperature_zero", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_chat_temperature_zero"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertTrue(result.choices.first().message.content?.text().orEmpty().isNotEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testFinishReasonContentFilter(): Unit = runBlocking {
        // Chat response stopped by content filter with finish_reason of content_filter and null content
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Tell me something controversial\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.finish_reason_content_filter", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/finish_reason_content_filter"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertEquals("content_filter", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testFinishReasonLength(): Unit = runBlocking {
        // Chat response truncated due to max_tokens limit with finish_reason of length
        val req = MAPPER.readValue("{\"max_tokens\":5,\"messages\":[{\"content\":\"Tell me a long story\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.finish_reason_length", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/finish_reason_length"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertEquals("length", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testMultiTurnConversation(): Unit = runBlocking {
        // Multi-turn conversation with system, user, assistant, and follow-up user messages
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"What is 2 + 2?\",\"role\":\"user\"},{\"content\":\"2 + 2 equals 4.\",\"role\":\"assistant\"},{\"content\":\"And what is 4 + 4?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.multi_turn_conversation", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/multi_turn_conversation"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testParallelToolCalls(): Unit = runBlocking {
        // Chat request that results in parallel tool calls in the response
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"What is the weather in NYC and London?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"parallel_tool_calls\":true,\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.parallel_tool_calls", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/parallel_tool_calls"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertTrue(result.choices.first().message.toolCalls?.isNotEmpty() == true, "expected non-empty value")
        assertEquals(2, result.choices.first().message.toolCalls!!.size, "expected exactly 2 elements")
        assertEquals("tool_calls", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testResponseFormatJsonObject(): Unit = runBlocking {
        // Chat request with response_format json_object that returns valid JSON content
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Respond with JSON only.\",\"role\":\"system\"},{\"content\":\"Give me a user object with name and age fields.\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"type\":\"json_object\"}}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.response_format_json_object", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/response_format_json_object"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertTrue(result.choices.first().message.content?.text().orEmpty().isNotEmpty(), "expected non-empty value")
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testResponseFormatJsonSchema(): Unit = runBlocking {
        // Chat request with response_format json_schema that validates the output structure
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"What is the temperature in Paris today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"json_schema\":{\"name\":\"weather\",\"schema\":{\"properties\":{\"temp\":{\"type\":\"number\"}},\"required\":[\"temp\"],\"type\":\"object\"}},\"type\":\"json_schema\"}}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.response_format_json_schema", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/response_format_json_schema"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertTrue(result.choices.first().message.content?.text().orEmpty().isNotEmpty(), "expected non-empty value")
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testSeedParameter(): Unit = runBlocking {
        // Chat request with seed parameter for deterministic output; response includes system_fingerprint
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Pick a random number\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"seed\":42}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.seed_parameter", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/seed_parameter"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertTrue(result.systemFingerprint != null, "expected non-empty value")
        client.close()
    }

    @Test
    fun testStopSequences(): Unit = runBlocking {
        // Chat request with custom stop sequences that terminates generation at a stop token
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"List items until you see STOP\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stop\":[\"STOP\",\"END\"]}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.stop_sequences", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/stop_sequences"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testToolChoiceRequired(): Unit = runBlocking {
        // Chat request with tool_choice set to required forces the model to call a tool
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"What is the weather today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"required\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.tool_choice_required", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/tool_choice_required"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertTrue(result.choices.first().message.toolCalls?.isNotEmpty() == true, "expected non-empty value")
        assertEquals("get_weather", result.choices.first().message.toolCalls?.first()?.function?.name.orEmpty())
        assertEquals("tool_calls", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

    @Test
    fun testToolChoiceSpecific(): Unit = runBlocking {
        // Chat request with tool_choice specifying a particular function to call
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"What is the weather in Paris?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":{\"function\":{\"name\":\"get_weather\"},\"type\":\"function\"},\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"},{\"function\":{\"description\":\"Search the web for information\",\"name\":\"search_web\",\"parameters\":{\"properties\":{\"query\":{\"description\":\"The search query\",\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}},\"type\":\"function\"}]}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.tool_choice_specific", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/tool_choice_specific"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        assertTrue(result.choices.first().message.toolCalls?.isNotEmpty() == true, "expected non-empty value")
        assertEquals("get_weather", result.choices.first().message.toolCalls?.first()?.function?.name.orEmpty())
        assertEquals("tool_calls", result.choices.first().finishReason?.toWire().orEmpty())
        client.close()
    }

}
