// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:90fd1c197bdb22c1a86142dc813ef926e356cc47ff5865e08fee56ee8e254064
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.ChatCompletionRequest
import io.xberg.literllm.android.OcrRequest
import io.xberg.literllm.android.SearchRequest

/** E2e tests for category: contract. */
class ContractTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testBindingApiParity(): Unit = runBlocking {
        // Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Contract test\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.binding_api_parity", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/binding_api_parity"))
        val result = client.chat(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.choices.size, "expected exactly 1 elements")
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        assertEquals("stop", result.choices.first().finishReason?.toWire().orEmpty())
        assertEquals(6L, result.usage?.totalTokens!!)
        assertEquals("gpt-4o", result.model)
        client.close()
    }

    @Test
    fun testContractOcr(): Unit = runBlocking {
        // Verify ocr() method exists in all bindings
        val req = MAPPER.readValue("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/contract-test.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}", OcrRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.contract_ocr", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/contract_ocr"))
        val result = client.ocr(req)
        assertNotNull(result, "expected non-null result")
        client.close()
    }

    @Test
    fun testContractSearch(): Unit = runBlocking {
        // Verify search() method exists in all bindings
        val req = MAPPER.readValue("{\"model\":\"brave/web-search\",\"query\":\"contract test query\"}", SearchRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.contract_search", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/contract_search"))
        val result = client.search(req)
        assertNotNull(result, "expected non-null result")
        client.close()
    }

}
