// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:caa58820ddd4936a06d164680b877977fcd8362c979cc1575f3c6eb1fff54e33
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.EmbeddingRequest

/** E2e tests for category: embed. */
class EmbedTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testBatchEmbed(): Unit = runBlocking {
        // Embedding request with multiple input strings returns one embedding object per input
        val req = MAPPER.readValue("{\"input\":[\"Hello\",\"World\"],\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.batch_embed", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/batch_embed"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.data.size, "expected exactly 2 elements")
        assertEquals(5, result.data.first().embedding.size, "expected exactly 5 elements")
        client.close()
    }

    @Test
    fun testEdgeEmbedBatchInput(): Unit = runBlocking {
        // Embedding request with multiple inputs returns multiple embedding objects
        val req = MAPPER.readValue("{\"input\":[\"Hello world\",\"Goodbye world\"],\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_embed_batch_input", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_embed_batch_input"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.data.size, "expected exactly 2 elements")
        assertEquals(0, result.data.first().index)
        assertEquals(1, result.data.get(1).index)
        client.close()
    }

    @Test
    fun testEdgeEmbedEmptyInput(): Unit = runBlocking {
        // Embedding request with empty string input returns empty data array
        val req = MAPPER.readValue("{\"input\":\"\",\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_embed_empty_input", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_embed_empty_input"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(0, result.data.size, "expected exactly 0 elements")
        client.close()
    }

    @Test
    fun testEmbedBase64(): Unit = runBlocking {
        // Embedding request with encoding_format base64 decodes to a float array embedding
        val req = MAPPER.readValue("{\"encoding_format\":\"base64\",\"input\":\"Test input\",\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.embed_base64", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/embed_base64"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertEquals(4, result.data.first().embedding.size, "expected exactly 4 elements")
        client.close()
    }

    @Test
    fun testEmbedEncodingFormat(): Unit = runBlocking {
        // Embedding request with explicit encoding_format of float returns float array embeddings
        val req = MAPPER.readValue("{\"encoding_format\":\"float\",\"input\":\"Test input\",\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.embed_encoding_format", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/embed_encoding_format"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertEquals(5, result.data.first().embedding.size, "expected exactly 5 elements")
        client.close()
    }

    @Test
    fun testEmbedError401(): Unit = runBlocking {
        // 401 Unauthorized error on embedding request when API key is invalid
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.embed_error_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/embed_error_401"))
            client.embed(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testEmbedWithDimensions(): Unit = runBlocking {
        // Embedding request with explicit dimensions parameter returns embeddings of the requested size
        val req = MAPPER.readValue("{\"dimensions\":256,\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.embed_with_dimensions", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/embed_with_dimensions"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertEquals(8, result.data.first().embedding.size, "expected exactly 8 elements")
        client.close()
    }

    @Test
    fun testLocalEmbedOllama(): Unit = runBlocking {
        // Embedding request via Ollama local provider with all-minilm model
        val req = MAPPER.readValue("{\"input\":\"The quick brown fox jumps over the lazy dog\",\"model\":\"ollama/all-minilm\"}", EmbeddingRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.local_embed_ollama", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/local_embed_ollama"))
        val result = client.embed(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertEquals(32, result.data.first().embedding.size, "expected exactly 32 elements")
        client.close()
    }

}
