// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d43c9d9f63c45f1e362b39bb621f56d4cde185306815441b8e994cc5259164fc
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.CreateFileRequest

/** E2e tests for category: files. */
class FilesTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeFileEmptyList(): Unit = runBlocking {
        // List files when no files have been uploaded
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_file_empty_list", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_file_empty_list"))
        val result = client.listFiles()
        // not_error: covered by the bare Optional's own assertion
        assertEquals(0, result.data.size, "expected exactly 0 elements")
        client.close()
    }

    @Test
    fun testEdgeFileLargeUpload(): Unit = runBlocking {
        // Upload a large file successfully
        val req = MAPPER.readValue("{\"file\":\"eyJwcm9tcHQiOiAibGFyZ2UgdHJhaW5pbmcgZGF0YSJ9Cg==\",\"filename\":\"large_training_data.jsonl\",\"purpose\":\"fine-tune\"}", CreateFileRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_file_large_upload", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_file_large_upload"))
        val result = client.createFile(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.id.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testErrorFileAuth401(): Unit = runBlocking {
        // 401 Unauthorized when listing files with invalid API key
        assertFailsWith<Exception> {
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_file_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_file_auth_401"))
            client.listFiles()
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorFileNotFound(): Unit = runBlocking {
        // 404 Not Found when retrieving a nonexistent file
        assertFailsWith<Exception> {
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_file_not_found", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_file_not_found"))
            client.retrieveFile("file-nonexistent")
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeCreateFile(): Unit = runBlocking {
        // Upload a file for use with the API
        val req = MAPPER.readValue("{\"file\":\"eyJwcm9tcHQiOiAiaGVsbG8ifQo=\",\"filename\":\"training_data.jsonl\",\"purpose\":\"fine-tune\"}", CreateFileRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_create_file", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_create_file"))
        val result = client.createFile(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.id.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeDeleteFile(): Unit = runBlocking {
        // Delete an uploaded file
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_delete_file", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_delete_file"))
        val result = client.deleteFile("file-abc123")
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.id.isEmpty(), "expected non-empty value")
        assertEquals(true, result.deleted)
        client.close()
    }

    @Test
    fun testSmokeFileContent(): Unit = runBlocking {
        // Retrieve the content of an uploaded file
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_file_content", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_file_content"))
        val result = client.fileContent("file-abc123")
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeListFiles(): Unit = runBlocking {
        // List all uploaded files
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_list_files", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_list_files"))
        val result = client.listFiles()
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.data.size, "expected exactly 2 elements")
        client.close()
    }

    @Test
    fun testSmokeRetrieveFile(): Unit = runBlocking {
        // Retrieve metadata for an uploaded file
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_retrieve_file", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_retrieve_file"))
        val result = client.retrieveFile("file-abc123")
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.id.isEmpty(), "expected non-empty value")
        client.close()
    }

}
