// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1394589b0805b3eb3056ee44f025e6e6718de8860882ffdb267c5226c2f343fa
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.ModerationRequest

/** E2e tests for category: moderate. */
class ModerateTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeModerateAllCategories(): Unit = runBlocking {
        // Moderation response with multiple categories flagged
        val req = MAPPER.readValue("{\"input\":\"Extremely harmful content targeting multiple categories\",\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_moderate_all_categories", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_moderate_all_categories"))
        val result = client.moderate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertEquals(true, result.results.first().flagged)
        client.close()
    }

    @Test
    fun testEdgeModerateEmptyInput(): Unit = runBlocking {
        // Moderation with empty string input
        val req = MAPPER.readValue("{\"input\":\"\",\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_moderate_empty_input", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_moderate_empty_input"))
        val result = client.moderate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertEquals(false, result.results.first().flagged)
        client.close()
    }

    @Test
    fun testErrorModerateAuth401(): Unit = runBlocking {
        // 401 Unauthorized for moderation with invalid API key
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"input\":\"Hello\",\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_moderate_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_moderate_auth_401"))
            client.moderate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorModerateBadRequest(): Unit = runBlocking {
        // 400 Bad Request for moderation with invalid model
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"input\":\"Hello\",\"model\":\"nonexistent-moderation\"}", ModerationRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_moderate_bad_request", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_moderate_bad_request"))
            client.moderate(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeModerateBatch(): Unit = runBlocking {
        // Moderate multiple inputs in a single request
        val req = MAPPER.readValue("{\"input\":[\"Hello world\",\"Nice weather today\"],\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_moderate_batch", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_moderate_batch"))
        val result = client.moderate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        assertEquals(false, result.results.first().flagged)
        client.close()
    }

    @Test
    fun testSmokeModerateFlagged(): Unit = runBlocking {
        // Moderation detects flagged content
        val req = MAPPER.readValue("{\"input\":\"I want to hurt someone very badly\",\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_moderate_flagged", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_moderate_flagged"))
        val result = client.moderate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertEquals(true, result.results.first().flagged)
        client.close()
    }

    @Test
    fun testSmokeModerateSingle(): Unit = runBlocking {
        // Moderate a single non-flagged input
        val req = MAPPER.readValue("{\"input\":\"The weather is nice today.\",\"model\":\"omni-moderation-latest\"}", ModerationRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_moderate_single", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_moderate_single"))
        val result = client.moderate(req)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertEquals(false, result.results.first().flagged)
        client.close()
    }

}
