// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1beedf8465d8920dd6ff9ed755a447e7e635083f1d65911a5ce8c0d4eddf8a4f
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.ChatCompletionRequest

/** E2e tests for category: parity. */
class ParityTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testApiSurfaceParity(): Unit = runBlocking {
        // Canonical API surface definition for cross-binding parity verification
        val req = MAPPER.readValue("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}", ChatCompletionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.api_surface_parity", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/api_surface_parity"))
        val result = client.chat(req)
        assertNotNull(result, "expected non-null result")
        client.close()
    }

}
