// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d9d6b0561c4403d397aaaf9192e45baba04bafdd1d90defacfafa607bda18ab
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.CreateSpeechRequest

/** E2e tests for category: speech. */
class SpeechTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeSpeechAllVoices(): Unit = runBlocking {
        // Text-to-speech with specific voice selection
        val req = MAPPER.readValue("{\"input\":\"Hello world\",\"model\":\"tts-1\",\"voice\":\"nova\"}", CreateSpeechRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_speech_all_voices", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_speech_all_voices"))
        val result = client.speech(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testEdgeSpeechLongInput(): Unit = runBlocking {
        // Speech generation with a very long input text
        val req = MAPPER.readValue("{\"input\":\"This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.\",\"model\":\"tts-1\",\"voice\":\"echo\"}", CreateSpeechRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_speech_long_input", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_speech_long_input"))
        val result = client.speech(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testErrorSpeechAuth401(): Unit = runBlocking {
        // 401 Unauthorized for speech generation with invalid API key
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"input\":\"Hello\",\"model\":\"tts-1\",\"voice\":\"alloy\"}", CreateSpeechRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_speech_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_speech_auth_401"))
            client.speech(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorSpeechBadModel(): Unit = runBlocking {
        // 400 Bad Request for speech with unsupported model
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"input\":\"Hello\",\"model\":\"tts-nonexistent\",\"voice\":\"alloy\"}", CreateSpeechRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_speech_bad_model", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_speech_bad_model"))
            client.speech(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeSpeechBasic(): Unit = runBlocking {
        // Basic text-to-speech generation
        val req = MAPPER.readValue("{\"input\":\"Hello, world!\",\"model\":\"tts-1\",\"voice\":\"alloy\"}", CreateSpeechRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_speech_basic", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_speech_basic"))
        val result = client.speech(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeSpeechMp3Format(): Unit = runBlocking {
        // Text-to-speech with explicit MP3 response format
        val req = MAPPER.readValue("{\"input\":\"The quick brown fox jumps over the lazy dog.\",\"model\":\"tts-1-hd\",\"response_format\":\"mp3\",\"speed\":1.0,\"voice\":\"nova\"}", CreateSpeechRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_speech_mp3_format", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_speech_mp3_format"))
        val result = client.speech(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.isEmpty(), "expected non-empty value")
        client.close()
    }

}
