// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d7b8d1461bfa088a0fb73d51b5b9d45dd221aab006d3e33a95616ea10876b53
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.literllm.android.LiterLlm
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.literllm.android.CreateTranscriptionRequest

/** E2e tests for category: transcribe. */
class TranscribeTest {

    companion object {
        init {
            try {
                System.loadLibrary("literllm_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load literllm_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEdgeTranscribeEmptyAudio(): Unit = runBlocking {
        // Transcription of a silent or empty audio file returns empty text
        val req = MAPPER.readValue("{\"file\":\"silence.mp3\",\"model\":\"whisper-1\"}", CreateTranscriptionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_transcribe_empty_audio", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_transcribe_empty_audio"))
        val result = client.transcribe(req)
        // not_error: covered by the bare Optional's own assertion
        assertTrue(result.text.contains(""), "expected to contain: " + "")
        client.close()
    }

    @Test
    fun testEdgeTranscribeWithTimestamps(): Unit = runBlocking {
        // Transcription with verbose JSON response format including timestamp segments
        val req = MAPPER.readValue("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\",\"response_format\":\"verbose_json\"}", CreateTranscriptionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.edge_transcribe_with_timestamps", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/edge_transcribe_with_timestamps"))
        val result = client.transcribe(req)
        // not_error: covered by the bare Optional's own assertion
        assertFalse(result.text.isEmpty(), "expected non-empty value")
        assertEquals(3, result.segments!!.size, "expected exactly 3 elements")
        assertEquals(0, result.segments?.first()?.id!!)
        client.close()
    }

    @Test
    fun testErrorTranscribeAuth401(): Unit = runBlocking {
        // 401 Unauthorized for transcription with invalid API key
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}", CreateTranscriptionRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_transcribe_auth_401", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_transcribe_auth_401"))
            client.transcribe(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testErrorTranscribeBadFormat(): Unit = runBlocking {
        // 400 Bad Request when audio format is unsupported
        assertFailsWith<Exception> {
            val req = MAPPER.readValue("{\"file\":\"audio.xyz\",\"model\":\"whisper-1\"}", CreateTranscriptionRequest::class.java)
            val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.error_transcribe_bad_format", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/error_transcribe_bad_format"))
            client.transcribe(req)
            client.close()
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        Unit
    }

    @Test
    fun testSmokeTranscribeBasic(): Unit = runBlocking {
        // Basic audio transcription
        val req = MAPPER.readValue("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}", CreateTranscriptionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_transcribe_basic", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_transcribe_basic"))
        val result = client.transcribe(req)
        // not_error: covered by the bare Optional's own assertion
        assertTrue(result.text.contains("Hello, this is a test transcription."), "expected to contain: " + "Hello, this is a test transcription.")
        client.close()
    }

    @Test
    fun testSmokeTranscribeWithLanguage(): Unit = runBlocking {
        // Audio transcription with explicit language hint
        val req = MAPPER.readValue("{\"file\":\"audio_de.mp3\",\"language\":\"de\",\"model\":\"whisper-1\"}", CreateTranscriptionRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getProperty("mockServer.smoke_transcribe_with_language", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/smoke_transcribe_with_language"))
        val result = client.transcribe(req)
        // not_error: covered by the bare Optional's own assertion
        assertTrue(result.text.contains("Hallo, dies ist ein Testtranskription."), "expected to contain: " + "Hallo, dies ist ein Testtranskription.")
        client.close()
    }

}
