// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b37f6646a6368cfb63972f3c6622a0866673e90d3815c20f167d712de14ee4c
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
    name: "E2eSwift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    dependencies: [
        .package(url: "https://github.com/xberg-io/liter-llm", branch: "release/swift/2.0.0"),
    ],
    targets: [
        .testTarget(
            name: "LiterLlmE2ETests",
            dependencies: [.product(name: "LiterLlm", package: "liter-llm")]
        ),
    ]
)
