// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8854b0c44c6364d2769831e8190bbf88e06e7f39012b457b310a1f21c136e0c
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, ToolType, type Message, type ResponseFormat } from "@xberg-io/liter-llm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("chat", () => {

	it("developer_message: Chat request that includes a developer role message alongside user messages", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/developer_message`);
		const result = await client.chat({ messages: [{ role: "developer", developer: { content: "You are a coding assistant. Always respond with concise code examples." } } as Message, { role: "user", user: { content: "How do I reverse a string in Python?" } } as Message], model: "gpt-4" });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.message?.content ?? "")).toBe("s[::-1]");
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");

	}, 30000);

	it("edge_chat_max_tokens: Chat request with max_tokens=1 terminates with length finish_reason", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_chat_max_tokens`);
		const result = await client.chat({ maxTokens: 1, messages: [{ role: "user", user: { content: "Write a story" } } as Message], model: "gpt-4" });
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("length");
    {
        const _v = result.choices?.[0]?.message?.content;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("edge_chat_system_only: Chat request with system message and user message", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_chat_system_only`);
		const result = await client.chat({ messages: [{ role: "system", system: { content: "You are a helpful and concise assistant" } } as Message, { role: "user", user: { content: "Hi" } } as Message], model: "gpt-4" });
    {
        const _v = result.choices?.[0]?.message?.content;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("edge_chat_temperature_zero: Chat request with temperature=0 for deterministic responses", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_chat_temperature_zero`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "Say hello" } } as Message], model: "gpt-4", temperature: 0 });
    {
        const _v = result.choices?.[0]?.message?.content;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("finish_reason_content_filter: Chat response stopped by content filter with finish_reason of content_filter and null content", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/finish_reason_content_filter`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "Tell me something controversial" } } as Message], model: "gpt-4" });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("content_filter");

	}, 30000);

	it("finish_reason_length: Chat response truncated due to max_tokens limit with finish_reason of length", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/finish_reason_length`);
		const result = await client.chat({ maxTokens: 5, messages: [{ role: "user", user: { content: "Tell me a long story" } } as Message], model: "gpt-4" });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("length");

	}, 30000);

	it("multi_turn_conversation: Multi-turn conversation with system, user, assistant, and follow-up user messages", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/multi_turn_conversation`);
		const result = await client.chat({ messages: [{ role: "system", system: { content: "You are a helpful assistant." } } as Message, { role: "user", user: { content: "What is 2 + 2?" } } as Message, { role: "assistant", assistant: { content: "2 + 2 equals 4." } } as Message, { role: "user", user: { content: "And what is 4 + 4?" } } as Message], model: "gpt-4" });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.message?.content ?? "")).toBe("4 + 4 equals 8.");
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");

	}, 30000);

	it("parallel_tool_calls: Chat request that results in parallel tool calls in the response", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/parallel_tool_calls`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "What is the weather in NYC and London?" } } as Message], model: "gpt-4", parallelToolCalls: true, tools: [{ function: { description: "Get the current weather for a given location", name: "get_weather", parameters: { properties: { location: { description: "The city name", type: "string" } }, required: ["location"], type: "object" } }, toolType: ToolType.Function }] });
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices?.[0]?.message?.toolCalls;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.choices?.[0]?.message?.toolCalls.length).toBe(2);
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("tool_calls");

	}, 30000);

	it("response_format_json_object: Chat request with response_format json_object that returns valid JSON content", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/response_format_json_object`);
		const result = await client.chat({ messages: [{ role: "system", system: { content: "Respond with JSON only." } } as Message, { role: "user", user: { content: "Give me a user object with name and age fields." } } as Message], model: "gpt-4", responseFormat: { type: "json_object" } as ResponseFormat });
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices?.[0]?.message?.content;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");

	}, 30000);

	it("response_format_json_schema: Chat request with response_format json_schema that validates the output structure", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/response_format_json_schema`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "What is the temperature in Paris today?" } } as Message], model: "gpt-4", responseFormat: { jsonSchema: { name: "weather", schema: { properties: { temp: { type: "number" } }, required: ["temp"], type: "object" } }, type: "json_schema" } as ResponseFormat });
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices?.[0]?.message?.content;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");

	}, 30000);

	it("seed_parameter: Chat request with seed parameter for deterministic output; response includes system_fingerprint", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/seed_parameter`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "Pick a random number" } } as Message], model: "gpt-4", seed: 42 });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");
    {
        const _v = result.systemFingerprint;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("stop_sequences: Chat request with custom stop sequences that terminates generation at a stop token", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/stop_sequences`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "List items until you see STOP" } } as Message], model: "gpt-4", stop: ["STOP", "END"] });
    expect(result.choices.length).toBe(1);
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("stop");

	}, 30000);

	it("tool_choice_required: Chat request with tool_choice set to required forces the model to call a tool", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/tool_choice_required`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "What is the weather today?" } } as Message], model: "gpt-4", toolChoice: "required", tools: [{ function: { description: "Get the current weather for a given location", name: "get_weather", parameters: { properties: { location: { description: "The city name", type: "string" } }, required: ["location"], type: "object" } }, toolType: ToolType.Function }] });
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices?.[0]?.message?.toolCalls;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.choices?.[0]?.message?.toolCalls?.[0]?.function.name).toBe("get_weather");
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("tool_calls");

	}, 30000);

	it("tool_choice_specific: Chat request with tool_choice specifying a particular function to call", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/tool_choice_specific`);
		const result = await client.chat({ messages: [{ role: "user", user: { content: "What is the weather in Paris?" } } as Message], model: "gpt-4", toolChoice: { function: { name: "get_weather" }, type: "function" }, tools: [{ function: { description: "Get the current weather for a given location", name: "get_weather", parameters: { properties: { location: { description: "The city name", type: "string" } }, required: ["location"], type: "object" } }, toolType: ToolType.Function }, { function: { description: "Search the web for information", name: "search_web", parameters: { properties: { query: { description: "The search query", type: "string" } }, required: ["query"], type: "object" } }, toolType: ToolType.Function }] });
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices?.[0]?.message?.toolCalls;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.choices?.[0]?.message?.toolCalls?.[0]?.function.name).toBe("get_weather");
    expect((result.choices?.[0]?.finishReason ?? "")).toBe("tool_calls");

	}, 30000);

});
