# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4ef27b320aef4cd9172debc046022bc586a87dbf94f919491775b5dd8c75036
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "liter_llm"
  spec.version = "1.19.3"
  spec.authors       = ["Na'aman Hirschfeld"]
  spec.summary       = "Universal LLM API client with Rust-powered polyglot bindings."
  spec.description   = "Universal LLM API client with Rust-powered polyglot bindings."
  spec.homepage      = "https://github.com/xberg-io/liter-llm"

  spec.license       = "MIT"

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["keywords"] = %w[anthropic api-client llm openai].join(",")
  spec.metadata["rubygems_mfa_required"] = "true"

  candidate_files    = Dir.glob(%w[README* LICENSE* lib/**/* ext/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/liter_llm_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9.130", "< 0.10"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
