// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:492f7b93b5199928d0f6aed7fa37561c27803d967396ae063896f8720aa347d8
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: chat.
final class ChatTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testDeveloperMessage() async throws {
        // Chat request that includes a developer role message alongside user messages
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"You are a coding assistant. Always respond with concise code examples.\",\"role\":\"developer\"},{\"content\":\"How do I reverse a string in Python?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/developer_message")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_7ba7bc0e_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_7ba7bc0e_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "s[::-1]")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testEdgeChatMaxTokens() async throws {
        // Chat request with max_tokens=1 terminates with length finish_reason
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":1,\"messages\":[{\"content\":\"Write a story\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_chat_max_tokens")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        let _vec_choices_equals_3ce619d2_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_3ce619d2_1[0].finishReason()?.toString() ?? ""), "length")
        let _vec_choices_not_empty_fc8f36c_1 = result.choices()
        XCTAssertFalse(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_not_empty_fc8f36c_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? "").isEmpty, "expected non-empty value")
    }

    func testEdgeChatSystemOnly() async throws {
        // Chat request with system message and user message
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"You are a helpful and concise assistant\",\"role\":\"system\"},{\"content\":\"Hi\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_chat_system_only")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        let _vec_choices_not_empty_fc8f36c_1 = result.choices()
        XCTAssertFalse(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_not_empty_fc8f36c_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? "").isEmpty, "expected non-empty value")
    }

    func testEdgeChatTemperatureZero() async throws {
        // Chat request with temperature=0 for deterministic responses
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_chat_temperature_zero")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        let _vec_choices_not_empty_fc8f36c_1 = result.choices()
        XCTAssertFalse(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_not_empty_fc8f36c_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? "").isEmpty, "expected non-empty value")
    }

    func testFinishReasonContentFilter() async throws {
        // Chat response stopped by content filter with finish_reason of content_filter and null content
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Tell me something controversial\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/finish_reason_content_filter")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_eda78af_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_eda78af_1[0].finishReason()?.toString() ?? ""), "content_filter")
    }

    func testFinishReasonLength() async throws {
        // Chat response truncated due to max_tokens limit with finish_reason of length
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":5,\"messages\":[{\"content\":\"Tell me a long story\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/finish_reason_length")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_3ce619d2_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_3ce619d2_1[0].finishReason()?.toString() ?? ""), "length")
    }

    func testMultiTurnConversation() async throws {
        // Multi-turn conversation with system, user, assistant, and follow-up user messages
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"What is 2 + 2?\",\"role\":\"user\"},{\"content\":\"2 + 2 equals 4.\",\"role\":\"assistant\"},{\"content\":\"And what is 4 + 4?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/multi_turn_conversation")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_c0c61677_1 = result.choices()
        XCTAssertEqual(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_equals_c0c61677_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? ""), "4 + 4 equals 8.")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testParallelToolCalls() async throws {
        // Chat request that results in parallel tool calls in the response
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the weather in NYC and London?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"parallel_tool_calls\":true,\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/parallel_tool_calls")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19_1 = result.choices()
        XCTAssertGreaterThan(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_not_empty_c4dcde19_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 0, "expected non-empty value")
        let _vec_choices_count_equals_325c94b_1 = result.choices()
        XCTAssertEqual(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_count_equals_325c94b_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 2)
        let _vec_choices_equals_1c1cc717_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717_1[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

    func testResponseFormatJsonObject() async throws {
        // Chat request with response_format json_object that returns valid JSON content
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Respond with JSON only.\",\"role\":\"system\"},{\"content\":\"Give me a user object with name and age fields.\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"type\":\"json_object\"}}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/response_format_json_object")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_fc8f36c_1 = result.choices()
        XCTAssertFalse(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_not_empty_fc8f36c_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? "").isEmpty, "expected non-empty value")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testResponseFormatJsonSchema() async throws {
        // Chat request with response_format json_schema that validates the output structure
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the temperature in Paris today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"json_schema\":{\"name\":\"weather\",\"schema\":{\"properties\":{\"temp\":{\"type\":\"number\"}},\"required\":[\"temp\"],\"type\":\"object\"}},\"type\":\"json_schema\"}}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/response_format_json_schema")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_fc8f36c_1 = result.choices()
        XCTAssertFalse(((try JSONDecoder().decode(LiterLlm.AssistantContent?.self, from: Data((_vec_choices_not_empty_fc8f36c_1[0].message().content()?.toString() ?? "null").utf8)))?.text() ?? "").isEmpty, "expected non-empty value")
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testSeedParameter() async throws {
        // Chat request with seed parameter for deterministic output; response includes system_fingerprint
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Pick a random number\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"seed\":42}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/seed_parameter")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertTrue(result.systemFingerprint() != nil, "expected non-empty value")
    }

    func testStopSequences() async throws {
        // Chat request with custom stop sequences that terminates generation at a stop token
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"List items until you see STOP\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stop\":[\"STOP\",\"END\"]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/stop_sequences")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testToolChoiceRequired() async throws {
        // Chat request with tool_choice set to required forces the model to call a tool
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the weather today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"required\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/tool_choice_required")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19_1 = result.choices()
        XCTAssertGreaterThan(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_not_empty_c4dcde19_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 0, "expected non-empty value")
        let _vec_choices_equals_24d078d5_1 = result.choices()
        let _json_nav_24d078d5: Any? = (((((((try? JSONSerialization.jsonObject(with: Data(_vec_choices_equals_24d078d5_1[0].message().toolCalls().toString().utf8)))) as? [Any]).flatMap { $0.dropFirst(0).first }) as? [String: Any])?["function"]) as? [String: Any])?["name"]
        XCTAssertEqual((_json_nav_24d078d5 as? String) ?? "", "get_weather")
        let _vec_choices_equals_1c1cc717_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717_1[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

    func testToolChoiceSpecific() async throws {
        // Chat request with tool_choice specifying a particular function to call
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the weather in Paris?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":{\"function\":{\"name\":\"get_weather\"},\"type\":\"function\"},\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"},{\"function\":{\"description\":\"Search the web for information\",\"name\":\"search_web\",\"parameters\":{\"properties\":{\"query\":{\"description\":\"The search query\",\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/tool_choice_specific")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19_1 = result.choices()
        XCTAssertGreaterThan(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_not_empty_c4dcde19_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 0, "expected non-empty value")
        let _vec_choices_equals_24d078d5_1 = result.choices()
        let _json_nav_24d078d5: Any? = (((((((try? JSONSerialization.jsonObject(with: Data(_vec_choices_equals_24d078d5_1[0].message().toolCalls().toString().utf8)))) as? [Any]).flatMap { $0.dropFirst(0).first }) as? [String: Any])?["function"]) as? [String: Any])?["name"]
        XCTAssertEqual((_json_nav_24d078d5 as? String) ?? "", "get_weather")
        let _vec_choices_equals_1c1cc717_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717_1[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

}
