// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e9a5f23e9c18a7e13c28b70529465f429c35186800ac56bf7e8567561a1486b
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: list-models.
final class ListModelsTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testEmptyModelList() async throws {
        // List models response returns an empty data array when no models are available
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/empty_model_list")
        let result = try await _client.listModels()
        // not_error: covered by try propagation
        XCTAssertGreaterThanOrEqual(result.data.count, 0)
        XCTAssertEqual(result.data.count, 0)
    }

    func testListModelsError401() async throws {
        // 401 Unauthorized error on list models request when API key is invalid
        do {
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/list_models_error_401")
            _ = try await _client.listModels()
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testListModelsError500() async throws {
        // 500 Internal Server Error when listing models due to server failure
        do {
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/list_models_error_500")
            _ = try await _client.listModels()
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'ServerError' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testListModelsFiltered() async throws {
        // List models response with multiple model objects
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/list_models_filtered")
        let result = try await _client.listModels()
        // not_error: covered by try propagation
        XCTAssertGreaterThanOrEqual(result.data.count, 5)
        XCTAssertEqual(result.data[0].object, "model")
    }

}
