// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:00391551304a5a6663e4ddb4cf7cb90dc1f011682d878139f92b26e7cca42149
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: rerank.
final class RerankTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testEdgeRerankEmptyQuery() async throws {
        // Reranking with an empty query string
        let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"Some document\",\"Another document\"],\"model\":\"rerank-v3.5\",\"query\":\"\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_rerank_empty_query")
        let result = try await _client.rerank(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results().count, 2)
    }

    func testEdgeRerankSingleDoc() async throws {
        // Reranking with only a single document
        let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"Artificial intelligence is the simulation of human intelligence.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is AI?\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_rerank_single_doc")
        let result = try await _client.rerank(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results().count, 1)
        let _vec_results_greater_than_871844e6_1 = result.results()
        XCTAssertGreaterThan(_vec_results_greater_than_871844e6_1[0].relevanceScore(), 0.9)
    }

    func testErrorRerankAuth401() async throws {
        // 401 Unauthorized for reranking with invalid API key
        do {
            let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"doc1\"],\"model\":\"rerank-v3.5\",\"query\":\"test\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_rerank_auth_401")
            _ = try await _client.rerank(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testErrorRerankBadRequest() async throws {
        // 400 Bad Request for reranking with invalid model
        do {
            let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"doc1\"],\"model\":\"nonexistent-rerank\",\"query\":\"test\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_rerank_bad_request")
            _ = try await _client.rerank(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSmokeRerankBasic() async throws {
        // Basic reranking of documents against a query
        let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"Machine learning is a subset of AI.\",\"The weather is sunny today.\",\"Deep learning uses neural networks.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is machine learning?\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_rerank_basic")
        let result = try await _client.rerank(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results().count, 3)
        let _vec_results_greater_than_871844e6_1 = result.results()
        XCTAssertGreaterThan(_vec_results_greater_than_871844e6_1[0].relevanceScore(), 0.9)
    }

    func testSmokeRerankReturnDocs() async throws {
        // Reranking with return_documents flag to include document text
        let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"Rust is a systems programming language.\",\"Iron rusts when exposed to water.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Rust?\",\"return_documents\":true}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_rerank_return_docs")
        let result = try await _client.rerank(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results().count, 2)
        let _vec_results_not_empty_654ffcd5_1 = result.results()
        XCTAssertTrue(_vec_results_not_empty_654ffcd5_1[0].document() != nil, "expected non-empty value")
        let _vec_results_greater_than_871844e6_1 = result.results()
        XCTAssertGreaterThan(_vec_results_greater_than_871844e6_1[0].relevanceScore(), 0.9)
    }

    func testSmokeRerankWithTopN() async throws {
        // Reranking with top_n parameter to limit results
        let _req = try LiterLlm.rerankRequestFromJson("{\"documents\":[\"Python is a programming language.\",\"Cats are cute animals.\",\"Python was created by Guido van Rossum.\",\"The sun is a star.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Python?\",\"top_n\":2}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_rerank_with_top_n")
        let result = try await _client.rerank(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results().count, 2)
        let _vec_results_greater_than_871844e6_1 = result.results()
        XCTAssertGreaterThan(_vec_results_greater_than_871844e6_1[0].relevanceScore(), 0.9)
    }

}
