// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:263e5380fbe740d52f29e5bea8a9697790b659a7bc501c8c823bf368d49e586e
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: search.
final class SearchTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testSearchBasic() async throws {
        // Basic web search request with a simple query
        let _req = try LiterLlm.searchRequestFromJson("{\"model\":\"brave/web-search\",\"query\":\"What is Rust programming language?\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/search_basic")
        do {
            _ = try await _client.search(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

    func testSearchEmptyResults() async throws {
        // Web search with a query that returns no results
        let _req = try LiterLlm.searchRequestFromJson("{\"model\":\"brave/web-search\",\"query\":\"xyznonexistent12345xyz\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/search_empty_results")
        do {
            _ = try await _client.search(_req)
        } catch {
            XCTFail("expected call not to throw: \(error)")
        }
    }

    func testSearchError400() async throws {
        // 400 Bad Request error when search query is empty
        do {
            let _req = try LiterLlm.searchRequestFromJson("{\"model\":\"brave/web-search\",\"query\":\"\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/search_error_400")
            _ = try await _client.search(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSearchError401() async throws {
        // 401 Unauthorized error on web search due to invalid API credentials
        do {
            let _req = try LiterLlm.searchRequestFromJson("{\"model\":\"brave/web-search\",\"query\":\"test\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/search_error_401")
            _ = try await _client.search(_req)
            XCTFail("expected to throw")
        } catch {
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSearchWithMaxResults() async throws {
        // Search request with max_results parameter limiting response count
        let _req = try LiterLlm.searchRequestFromJson("{\"max_results\":2,\"model\":\"brave/web-search\",\"query\":\"Rust programming\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/search_with_max_results")
        let result = try await _client.search(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.results.count, 2)
    }

}
