// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e8da9544e5acb5dd8805c270015fa4da2709d3735893b7565b1497a2558e420
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: tool-calling.
final class ToolCallingTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testAnthropicToolCalling() async throws {
        // Chat request to Anthropic provider with a tool definition; assistant responds with a tool call
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":256,\"messages\":[{\"content\":\"What is the weather in London?\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and country, e.g. London, UK\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/anthropic_tool_calling")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19_1 = result.choices()
        XCTAssertGreaterThan(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_not_empty_c4dcde19_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 0, "expected non-empty value")
        let _vec_choices_equals_24d078d5_1 = result.choices()
        let _json_nav_24d078d5: Any? = (((((((try? JSONSerialization.jsonObject(with: Data(_vec_choices_equals_24d078d5_1[0].message().toolCalls().toString().utf8)))) as? [Any]).flatMap { $0.dropFirst(0).first }) as? [String: Any])?["function"]) as? [String: Any])?["name"]
        XCTAssertEqual((_json_nav_24d078d5 as? String) ?? "", "get_weather")
        let _vec_choices_equals_1c1cc717_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717_1[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

    func testSingleToolCall() async throws {
        // Chat request with a tool definition; assistant responds with a tool call
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the weather in San Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and state, e.g. San Francisco, CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/single_tool_call")
        let result = try await _client.chat(_req)
        // not_error: covered by try propagation
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19_1 = result.choices()
        XCTAssertGreaterThan(((try? JSONSerialization.jsonObject(with: Data(_vec_choices_not_empty_c4dcde19_1[0].message().toolCalls().toString().utf8))) as? [Any])?.count ?? 0, 0, "expected non-empty value")
        let _vec_choices_equals_24d078d5_1 = result.choices()
        let _json_nav_24d078d5: Any? = (((((((try? JSONSerialization.jsonObject(with: Data(_vec_choices_equals_24d078d5_1[0].message().toolCalls().toString().utf8)))) as? [Any]).flatMap { $0.dropFirst(0).first }) as? [String: Any])?["function"]) as? [String: Any])?["name"]
        XCTAssertEqual((_json_nav_24d078d5 as? String) ?? "", "get_weather")
        let _vec_choices_equals_1c1cc717_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717_1[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

}
