// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c491f33db94f74b95859f0859a97edb7a5bf69c5c3428ed3de4efa26e019060e
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionRequest, WasmOcrRequest, WasmSearchRequest, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions, WasmFinishReason } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("contract", () => {

	it("binding_api_parity: Verify all bindings expose the full API surface — constructor accepts all config options and every method exists", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/binding_api_parity`);
		const result = await client.chat((() => { const _u0 = WasmChatCompletionRequest.default(); _u0.messages = [{ content: "Contract test", role: "user" }]; _u0.model = "openai/gpt-4o"; return _u0; })());
    expect(result.choices.length).toBe(1);
    expect((result.choices[0].message.content ?? "")).toBe("OK");
    expect(result.choices[0].finishReason).toBe("stop");
    expect(Number(result.usage?.totalTokens)).toBe(6);
    expect(result.model).toBe("gpt-4o");

	}, 30000);

	it("contract_ocr: Verify ocr() method exists in all bindings", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/contract_ocr`);
		const result = await client.ocr((() => { const _u0 = WasmOcrRequest.default(); _u0.document = { type: "document_url", url: "https://example.com/contract-test.pdf" }; _u0.model = "mistral/mistral-ocr-latest"; return _u0; })());
    expect(result).toBeDefined();

	}, 30000);

	it("contract_search: Verify search() method exists in all bindings", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/contract_search`);
		const result = await client.search((() => { const _u0 = WasmSearchRequest.default(); _u0.model = "brave/web-search"; _u0.query = "contract test query"; return _u0; })());
    expect(result).toBeDefined();

	}, 30000);

});
