// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aea6b471da3755f1a6de8f91934117f45b46d15a0e6de76c1131e02bd7e7f1c9
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionRequest, WasmEmbeddingRequest, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions, WasmEmbeddingFormat } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("embed", () => {

	it("batch_embed: Embedding request with multiple input strings returns one embedding object per input", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/batch_embed`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.input = ["Hello", "World"]; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(2);
    expect(result.data[0].embedding.length).toBe(5);

	}, 30000);

	it("edge_embed_batch_input: Embedding request with multiple inputs returns multiple embedding objects", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_embed_batch_input`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.input = ["Hello world", "Goodbye world"]; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(2);
    expect(Number(result.data[0].index)).toBe(0);
    expect(Number(result.data[1].index)).toBe(1);

	}, 30000);

	it("edge_embed_empty_input: Embedding request with empty string input returns empty data array", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_embed_empty_input`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.input = ""; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(0);

	}, 30000);

	it("embed_base64: Embedding request with encoding_format base64 decodes to a float array embedding", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/embed_base64`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.encodingFormat = WasmEmbeddingFormat.Base64; _u0.input = "Test input"; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(1);
    expect(result.data[0].embedding.length).toBe(4);

	}, 30000);

	it("embed_encoding_format: Embedding request with explicit encoding_format of float returns float array embeddings", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/embed_encoding_format`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.encodingFormat = WasmEmbeddingFormat.Float; _u0.input = "Test input"; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(1);
    expect(result.data[0].embedding.length).toBe(5);

	}, 30000);

	it("embed_error_401: 401 Unauthorized error on embedding request when API key is invalid", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/embed_error_401`);
		await expect(async () => {
			await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.input = "Hello world"; _u0.model = "text-embedding-3-small"; return _u0; })());
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("embed_with_dimensions: Embedding request with explicit dimensions parameter returns embeddings of the requested size", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/embed_with_dimensions`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.dimensions = 256; _u0.input = "Hello world"; _u0.model = "text-embedding-3-small"; return _u0; })());
    expect(result.data.length).toBe(1);
    expect(result.data[0].embedding.length).toBe(8);

	}, 30000);

	it("local_embed_ollama: Embedding request via Ollama local provider with all-minilm model", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/local_embed_ollama`);
		const result = await client.embed((() => { const _u0 = WasmEmbeddingRequest.default(); _u0.input = "The quick brown fox jumps over the lazy dog"; _u0.model = "ollama/all-minilm"; return _u0; })());
    expect(result.data.length).toBe(1);
    expect(result.data[0].embedding.length).toBe(32);

	}, 30000);

});
