// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f395b69bbc4807288cea5842bb929e7beac1e5e192a19a5943c4c319fb60a4a6
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("files", () => {

	it("edge_file_empty_list: List files when no files have been uploaded", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_file_empty_list`);
		const result = await client.listFiles(undefined);
    expect(result.data.length).toBe(0);

	}, 30000);

	it("error_file_auth_401: 401 Unauthorized when listing files with invalid API key", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/error_file_auth_401`);
		await expect(async () => {
			await client.listFiles(undefined);
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("error_file_not_found: 404 Not Found when retrieving a nonexistent file", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/error_file_not_found`);
		await expect(async () => {
			await client.retrieveFile("file-nonexistent");
		}).rejects.toThrow();
		// skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("smoke_delete_file: Delete an uploaded file", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/smoke_delete_file`);
		const result = await client.deleteFile("file-abc123");
    {
        const _v = result.id;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.deleted).toBe(true);

	}, 30000);

	it("smoke_list_files: List all uploaded files", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/smoke_list_files`);
		const result = await client.listFiles(undefined);
    expect(result.data.length).toBe(2);

	}, 30000);

	it("smoke_retrieve_file: Retrieve metadata for an uploaded file", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/smoke_retrieve_file`);
		const result = await client.retrieveFile("file-abc123");
    {
        const _v = result.id;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

});
