// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7cffe4ee7aea4695ca51010fd49b7302f0ce3241d30605bb7752c80a2cc3b667
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionRequest, WasmCreateSpeechRequest, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("speech", () => {

	it("edge_speech_all_voices: Text-to-speech with specific voice selection", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_speech_all_voices`);
		const result = await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "Hello world"; _u0.model = "tts-1"; _u0.voice = "nova"; return _u0; })());
    {
        const _v = result;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("edge_speech_long_input: Speech generation with a very long input text", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/edge_speech_long_input`);
		const result = await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input."; _u0.model = "tts-1"; _u0.voice = "echo"; return _u0; })());
    {
        const _v = result;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("error_speech_auth_401: 401 Unauthorized for speech generation with invalid API key", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/error_speech_auth_401`);
		await expect(async () => {
			await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "Hello"; _u0.model = "tts-1"; _u0.voice = "alloy"; return _u0; })());
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("error_speech_bad_model: 400 Bad Request for speech with unsupported model", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/error_speech_bad_model`);
		await expect(async () => {
			await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "Hello"; _u0.model = "tts-nonexistent"; _u0.voice = "alloy"; return _u0; })());
		}).rejects.toThrow();
		// skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("smoke_speech_basic: Basic text-to-speech generation", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/smoke_speech_basic`);
		const result = await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "Hello, world!"; _u0.model = "tts-1"; _u0.voice = "alloy"; return _u0; })());
    {
        const _v = result;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

	it("smoke_speech_mp3_format: Text-to-speech with explicit MP3 response format", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/smoke_speech_mp3_format`);
		const result = await client.speech((() => { const _u0 = WasmCreateSpeechRequest.default(); _u0.input = "The quick brown fox jumps over the lazy dog."; _u0.model = "tts-1-hd"; _u0.responseFormat = "mp3"; _u0.speed = 1.0; _u0.voice = "nova"; return _u0; })());
    {
        const _v = result;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }

	}, 30000);

});
