// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:13c88522c6e487bafa31ca75d3b22cb476b2919d49dcb3eef87d65250bed0c1e
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionRequest, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions, WasmFinishReason, WasmToolType } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("tool-calling", () => {

	it("anthropic_tool_calling: Chat request to Anthropic provider with a tool definition; assistant responds with a tool call", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/anthropic_tool_calling`);
		const result = await client.chat((() => { const _u0 = WasmChatCompletionRequest.default(); _u0.maxTokens = 256n; _u0.messages = [{ content: "What is the weather in London?", role: "user" }]; _u0.model = "anthropic/claude-3-5-sonnet-20241022"; _u0.toolChoice = "auto"; _u0.tools = [(() => { const _u1 = WasmChatCompletionTool.default(); _u1.function = (() => { const _u2 = WasmFunctionDefinition.default(); _u2.description = "Get the current weather for a given location"; _u2.name = "get_weather"; _u2.parameters = { properties: { location: { description: "The city and country, e.g. London, UK", type: "string" }, unit: { description: "The temperature unit to use", enum: ["celsius", "fahrenheit"], type: "string" } }, required: ["location"], type: "object" }; return _u2; })(); _u1.toolType = WasmToolType.Function; return _u1; })()]; return _u0; })());
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices[0].message.toolCalls;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.choices[0].message.toolCalls?.[0]?.function.name).toBe("get_weather");
    expect(result.choices[0].finishReason).toBe("tool_calls");

	}, 30000);

	it("single_tool_call: Chat request with a tool definition; assistant responds with a tool call", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/single_tool_call`);
		const result = await client.chat((() => { const _u0 = WasmChatCompletionRequest.default(); _u0.messages = [{ content: "What is the weather in San Francisco?", role: "user" }]; _u0.model = "gpt-4"; _u0.toolChoice = "auto"; _u0.tools = [(() => { const _u1 = WasmChatCompletionTool.default(); _u1.function = (() => { const _u2 = WasmFunctionDefinition.default(); _u2.description = "Get the current weather for a given location"; _u2.name = "get_weather"; _u2.parameters = { properties: { location: { description: "The city and state, e.g. San Francisco, CA", type: "string" }, unit: { description: "The temperature unit to use", enum: ["celsius", "fahrenheit"], type: "string" } }, required: ["location"], type: "object" }; return _u2; })(); _u1.toolType = WasmToolType.Function; return _u1; })()]; return _u0; })());
    expect(result.choices.length).toBe(1);
    {
        const _v = result.choices[0].message.toolCalls;
        if (typeof _v === "string" || Array.isArray(_v)) {
            expect(_v.length).toBeGreaterThan(0);
        } else {
            expect(_v).toBeDefined();
            expect(_v).not.toBeNull();
        }
    }
    expect(result.choices[0].message.toolCalls?.[0]?.function.name).toBe("get_weather");
    expect(result.choices[0].finishReason).toBe("tool_calls");

	}, 30000);

});
