// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3f1edeac16380dd628a985a9f85e190d31987ed8557b89b9a10ae4f4b88f3102
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionRequest, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions, WasmFinishReason } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("types", () => {

	it("all_message_types: Request with all message role types (system, user, assistant, tool) to verify round-trip serialization", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/all_message_types`);
		const result = await client.chat((() => { const _u0 = WasmChatCompletionRequest.default(); _u0.messages = [{ content: "You are a helpful assistant.", role: "system" }, { content: "What is the weather in Paris?", role: "user" }, { content: null, role: "assistant", tool_calls: [{ function: { arguments: "{\"location\": \"Paris, France\"}", name: "get_weather" }, id: "call_xyz789", type: "function" }] }, { content: "{\"temperature\": 18, \"unit\": \"celsius\", \"description\": \"Partly cloudy\"}", role: "tool", tool_call_id: "call_xyz789" }]; _u0.model = "gpt-4"; return _u0; })());
    expect(result.choices.length).toBe(1);
    expect(result.choices[0].finishReason).toBe("stop");

	}, 30000);

	it("multimodal_content: User message with mixed text and image_url content parts to verify multimodal serialization", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/multimodal_content`);
		const result = await client.chat((() => { const _u0 = WasmChatCompletionRequest.default(); _u0.maxTokens = 100n; _u0.messages = [{ content: [{ text: "What is in this image?", type: "text" }, { image_url: { detail: "low", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png" }, type: "image_url" }], role: "user" }]; _u0.model = "gpt-4o"; return _u0; })());
    expect(result.choices.length).toBe(1);
    expect(result.choices[0].finishReason).toBe("stop");

	}, 30000);

});
