// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0dca7c452a1137b295fbb3700bee9cdd399f3c9721f32e183492099dd6da4320
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { createClient, WasmChatCompletionTool, WasmFunctionDefinition, WasmStreamOptions } from "@xberg-io/liter-llm-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("list-models", () => {

	it("empty_model_list: List models response returns an empty data array when no models are available", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/empty_model_list`);
		const result = await client.listModels();
    expect(result.data.length).toBeGreaterThanOrEqual(0);
    expect(result.data.length).toBe(0);

	}, 30000);

	it("list_models_error_401: 401 Unauthorized error on list models request when API key is invalid", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/list_models_error_401`);
		await expect(async () => {
			await client.listModels();
		}).rejects.toThrow();
		// skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("list_models_error_500: 500 Internal Server Error when listing models due to server failure", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/list_models_error_500`);
		await expect(async () => {
			await client.listModels();
		}).rejects.toThrow();
		// skipped: declared error variant 'ServerError' not yet preserved as a distinct identity by this backend's generator
		// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
	}, 30000);

	it("list_models_filtered: List models response with multiple model objects", async () => {
		const client = createClient('test-key', `${process.env.MOCK_SERVER_URL}/fixtures/list_models_filtered`);
		const result = await client.listModels();
    expect(result.data.length).toBeGreaterThanOrEqual(5);
    expect(result.data[0].object).toBe("model");

	}, 30000);

});
