# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a40343f90ff1b2068380b5df416a2a43078d2c397a096428bf749cdf8bb63638
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'liter_llm'
require 'json'

RSpec.describe 'files' do

  it 'edge_file_empty_list: List files when no files have been uploaded' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_file_empty_list')
    result = client.list_files_async(nil)
    expect(result.data.length).to eq(0)

  end


  it 'edge_file_large_upload: Upload a large file successfully' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_file_large_upload')
    result = client.create_file_async(LiterLlm::CreateFileRequest.new(file: 'eyJwcm9tcHQiOiAibGFyZ2UgdHJhaW5pbmcgZGF0YSJ9Cg==', filename: 'large_training_data.jsonl', purpose: 'fine-tune'))
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)

  end


  it 'error_file_auth_401: 401 Unauthorized when listing files with invalid API key' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/error_file_auth_401')
    expect {
      client.list_files_async(nil)
    }.to raise_error(RuntimeError) # skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'error_file_not_found: 404 Not Found when retrieving a nonexistent file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/error_file_not_found')
    expect {
      client.retrieve_file_async('file-nonexistent')
    }.to raise_error(RuntimeError) # skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'smoke_create_file: Upload a file for use with the API' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_create_file')
    result = client.create_file_async(LiterLlm::CreateFileRequest.new(file: 'eyJwcm9tcHQiOiAiaGVsbG8ifQo=', filename: 'training_data.jsonl', purpose: 'fine-tune'))
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)

  end


  it 'smoke_delete_file: Delete an uploaded file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_delete_file')
    result = client.delete_file_async('file-abc123')
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)
    expect(result.deleted).to be(true)

  end


  it 'smoke_file_content: Retrieve the content of an uploaded file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_file_content')
    result = client.file_content_async('file-abc123')
    expect(result.respond_to?(:empty?) ? !result.empty? : !result.nil?).to be(true)

  end


  it 'smoke_list_files: List all uploaded files' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_list_files')
    result = client.list_files_async(nil)
    expect(result.data.length).to eq(2)

  end


  it 'smoke_retrieve_file: Retrieve metadata for an uploaded file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_retrieve_file')
    result = client.retrieve_file_async('file-abc123')
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)

  end

end
