// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e46ff8db3b71eb0d8680ec6ec9b97c7ced5121632fb3a56fe1d85481c49be19
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: custom_provider
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_ProviderAuth(t *testing.T) {
	// Tests custom provider with custom auth header
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"my-auth-model-v1"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/provider_auth"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterProvider(t *testing.T) {
	// Tests that a custom provider can be registered and routes requests
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"my-model-v1"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/register_provider"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
