// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:010c9f5195f5eb598c972a23f5cf6f20cb4d010db25320f40ea602bd4c007d6d
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: ocr
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_OcrError400(t *testing.T) {
	// 400 Bad Request error when OCR input has an invalid image format
	var req pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"invalid://url"},"model":"mistral/mistral-ocr-latest"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/ocr_error_400"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Ocr(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'BadRequest' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_OcrError401(t *testing.T) {
	// 401 Unauthorized error on OCR request due to invalid API credentials
	var req pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"https://example.com/doc.pdf"},"model":"mistral/mistral-ocr-latest"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/ocr_error_401"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Ocr(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'Authentication' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_OcrMultiPage(t *testing.T) {
	// OCR request returning multiple pages of document content
	var req pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"https://example.com/multipage.pdf"},"model":"mistral/mistral-ocr-latest"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/ocr_multi_page"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Ocr(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Pages), 2, "expected exactly 2 elements")
	if len(result.Pages) == 0 {
		t.Fatalf("expected non-empty %s", `result.Pages`)
	}
	if result.Pages[0].Index != 0 {
		t.Errorf("equals mismatch: got %v", result.Pages[0].Index)
	}
	if result.Pages[1].Index != 1 {
		t.Errorf("equals mismatch: got %v", result.Pages[1].Index)
	}
}

func Test_OcrUrlDocument(t *testing.T) {
	// OCR request with a document URL input
	var req pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"https://example.com/doc.pdf"},"model":"mistral/mistral-ocr-latest"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/ocr_url_document"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Ocr(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
