// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:12a1923069841b6f3262eec96709c3924516d7ce61699b73903a142f7c545235
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: parity
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_ApiSurfaceParity(t *testing.T) {
	// Canonical API surface definition for cross-binding parity verification
	var req pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4o"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/api_surface_parity"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
