// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:84548dd2b7ee75b5856114c98f78973e3246f421cde9dd9e31ddd39ed8d00c54
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: search
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/liter-llm/packages/go/v2"
)

func Test_SearchBasic(t *testing.T) {
	// Basic web search request with a simple query
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":"What is Rust programming language?"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/search_basic"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SearchEmptyResults(t *testing.T) {
	// Web search with a query that returns no results
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":"xyznonexistent12345xyz"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/search_empty_results"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SearchError400(t *testing.T) {
	// 400 Bad Request error when search query is empty
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":""}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/search_error_400"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'BadRequest' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_SearchError401(t *testing.T) {
	// 401 Unauthorized error on web search due to invalid API credentials
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":"test"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/search_error_401"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(req)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	// skipped: declared error variant 'Authentication' not substantiated by this backend's generated error type
	// skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
}

func Test_SearchWithMaxResults(t *testing.T) {
	// Search request with max_results parameter limiting response count
	var req pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"max_results":2,"model":"brave/web-search","query":"Rust programming"}`), &req); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/search_with_max_results"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Search(req)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Results), 2, "expected exactly 2 elements")
}
