// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:258a1b5dcfdacc28e2efe7fe78c50c6e2053ff08d82bbc85631959e7ba85c0d2
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: parity

use liter_llm::BatchClient;
use liter_llm::FileClient;
use liter_llm::LlmClient;
use liter_llm::ResponseClient;
mod common;
mod mock_server;
#[allow(unused_imports)]
use mock_server::{MockRoute, MockServer};

#[test]
fn test_api_surface_parity() {
    common::runtime().block_on(async {
    // Canonical API surface definition for cross-binding parity verification
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-parity001","model":"gpt-4o","object":"chat.completion"}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let req_json: serde_json::Value = serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4o"}"#).unwrap();
    let req = serde_json::from_value(req_json).unwrap();
    let client = liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let _ = client.chat(req).await.expect("call failed");
    });
}
